- src/core/gridGL/graphics/ViewportComponent.tsx
- src/core/gridGL/graphics/drawGridLines.ts
Simplifies grid drawing. Grid lines are limited to viewport bounds.
> simplify grid drawing

- package-lock.json
- package.json
- src/ui/components/qColorPicker.tsx
- src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
- src/ui/menus/TopBar/SubMenus/FormatMenu/formatMenuStyles.scss
- src/ui/menus/TopBar/SubMenus/FormatMenu/useGetBorderMenu.tsx
added new colors for 'fill color'
> Color palette and styles

- src/core/gridGL/interaction/keyboard/keyboardCell.ts
- src/core/gridGL/pixiApp/PixiApp.ts
> feat: support dragging when space is being pressed

- src/core/gridGL/interaction/keyboard/keyboardCell.ts
- src/core/gridGL/pixiApp/PixiApp.ts
Reverts quadratichq/quadratic#210
> revert feat: support dragging when space is being pressed

- src/core/gridGL/interaction/keyboard/keyboardViewport.ts
- src/core/gridGL/interaction/keyboard/useKeyboard.ts
- src/ui/menus/CommandPalette/ListItems/Format.tsx
- src/ui/menus/KeyboardShortcut.tsx
- src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
- src/ui/menus/TopBar/SubMenus/useGetSelection.ts
> feat: bold/italic keyboard shortcuts

- src/core/actions/clearBordersAction.ts
- src/core/actions/clearFormattingAction.ts
- src/core/actions/clipboard.ts
- src/core/gridDB/Cells/DeleteCells.ts
- src/core/transaction/sheetController.ts
- src/ui/menus/TopBar/SubMenus/useBorders.ts
- src/ui/menus/TopBar/SubMenus/useFormatCells.ts
Cut now takes formatting in a single transaction
> bug: Development Cut Formatting

- src/ui/menus/GoTo/GoTo.tsx
Fixes bug where the list item in the goto UI wouldn't submit the form.
> fix: goto list item click

- quadratic-core/src/formulas/ast.rs
- quadratic-core/src/formulas/cell_ref.rs
- quadratic-core/src/formulas/grid_proxy.rs
- quadratic-core/src/formulas/tests.rs
> Add circular array reference detection

- src/gridGL/pixiApp/PixiAppSettings.ts
- src/ui/menus/CodeEditor/CodeEditor.tsx
> a1 notation is always displayed when formula editor is open

- src/grid/actions/gridFile/SaveGridFile.ts
- src/ui/menus/CommandPalette/ListItems/File.tsx
- src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
> fix: preserve file name on download

- src/gridGL/QuadraticGrid.tsx
Make it so it doesn't disappear when you choose a border in the context menu.
> fix: context menu border menu

- src/gridGL/interaction/keyboard/keyboardViewport.ts
- src/quadratic/QuadraticApp.tsx
- src/ui/components/PresentationModeHint.tsx
> Small fixes

- src/constants/gridConstants.ts
- src/gridGL/helpers/zoom.ts
- src/gridGL/interaction/keyboard/keyboardViewport.ts
- src/gridGL/interaction/keyboard/useKeyboard.ts
- src/gridGL/pixiApp/PixiApp.ts
- src/ui/menus/CommandPalette/ListItems/View.tsx
- src/ui/menus/TopBar/ZoomDropdown.tsx
> Zoom to selection

- src/debugFlags.ts
- src/gridGL/pixiOverride/Wheel.ts
Fixed #359 (maybe?)
- Added the blur handler for wheel. 
I wasn't able to reliably repro this, so it should be tested probably on a window's machine @HactarCE
> Viewport Gets Suck in Zoom Mode 

- src/debugFlags.ts
- src/grid/sheet/localFiles.ts
> Fix: turning Off Cell Types Can Unload File 

- src/ui/menus/CodeEditor/CodeEditor.tsx
> show loading in CodeEditor

- src/grid/actions/clipboard/clipboard.ts
- tsconfig.json
Fixes recent sentry errors titled "InvalidCharacterError"
> fixes copy paste encoding bug

- src/grid/sheet/GridOffsets.ts
- src/grid/sheet/GridOffsetsCache.ts
- src/gridGL/interaction/pointer/PointerHeading.ts
> fix bug with negative heading resizing moving the viewport

- src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
Added apple+O short cut to back to files menu item
> back to files shortcut

- src/gridGL/interaction/keyboard/keyboardCell.ts
Delete button works same as backspace to delete cells.
> added delete button

- src/debugFlags.ts
- src/gridGL/pixiApp/PixiAppSettings.ts
> Changing GridSettings properly re-renders cells

- src/grid/controller/sheetController.ts
- src/grid/controller/transaction.ts
> fix: make this.app conditional

- quadratic-core/src/formulas/functions/logic.rs
- quadratic-core/src/formulas/functions/lookup.rs
- quadratic-core/src/formulas/functions/operators.rs
- quadratic-core/src/formulas/functions/statistics.rs
- quadratic-core/src/formulas/functions/string.rs
- quadratic-core/src/formulas/tests.rs
I replaced a macro with an ordinary struct and moved tests for specific formula functions into the file where those functions are defined.
> Refactor formula tests

- src/gridGL/UI/cells/CellsLabels.ts
> fix clipping calculation to the right

- src/gridGL/quadrants/Quadrant.ts
Potential fix for blurry quadrants
> better resolution for quadrants for windows

- src/gridGL/interaction/pointer/PointerHeading.ts
- eventually this will also do the max-height calculation when we implement row wrapping
> double click to reset row size

- src/grid/controller/sheetController.ts
- src/gridGL/pixiApp/PixiApp.ts
Attempt to [fix new errors in sentry](https://quadratic.sentry.io/issues/4261168144/?project=6333132&referrer=digest-slack) that were introduced in #545
> fix: sentry errors

- src/gridGL/pixiApp/PixiAppSettings.ts
Fixes #575
Fixes #565 
Fixes #564
> fixes app.settings.setInteractionState

- src/debugFlags.ts
- src/grid/actions/clipboard/clipboard.ts
Fix copying of large data. Closes #584
> fix copying of large data

- app.json
- quadratic-api/src/routes/files/files.test.ts
- scripts/run-ci-build.sh
- src/api-client/apiClientSingleton.ts
Properly configured Heroku for API previews and Vercel for front end preview branches.
> Preview Branches

- public/index.html
- src/gridGL/loadAssets.ts
> preload OpenSans

- .github/workflows/test-python.yml
- package.json
- src/web-workers/pythonWebWorker/run_python.py
- tests-python/test.py
Fix Python so this Python code is now valid: `[c(1, 3), 20, c(2, 6), c(2, 3, "Sheet 2")]`
> Next fix array output

- src/ui/menus/CommandPalette/ListItems/Sheets.tsx
Command palette does not have Sheet commands when below editor
> Next sheet palette permission

- quadratic-core/src/grid/column.rs
- quadratic-core/src/grid/sheet/rendering.rs
- quadratic-core/src/wasm_bindings/controller/render.rs
- src/grid/controller/Grid.ts
- src/grid/sheet/Sheet.ts
- src/gridGL/cells/CellsSheet.ts
- src/gridGL/cells/CellsSheetPreloader.ts
- src/gridGL/pixiApp/Update.ts
- src/ui/menus/CodeEditor/Console.tsx
> Next renderer preloader

- src/gridGL/interaction/CellInput.tsx
> Improve CellInput

- quadratic-core/src/controller/operations.rs
- src/grid/controller/Sheets.ts
- src/grid/sheet/Sheet.ts
- src/ui/menus/SheetBar/SheetBarTab.tsx
> Next sheet tabs

- src/gridGL/UI/Cursor.ts
- src/gridGL/interaction/CellInput.tsx
> Next input box size

- quadratic-core/src/grid/formatting.rs
- quadratic-core/src/values/cellvalue.rs
- quadratic-core/src/wasm_bindings/controller/formatting.rs
- src/grid/controller/Grid.ts
- src/grid/sheet/Sheet.ts
- src/ui/menus/CommandPalette/ListItems/Format.tsx
- src/ui/menus/ContextMenu/FloatingContextMenu.tsx
- src/ui/menus/TopBar/SubMenus/NumberFormatMenu.tsx
- src/ui/menus/TopBar/SubMenus/formatCells.ts
> Next number menu

- quadratic-core/src/controller/cells.rs
- quadratic-core/src/controller/formatting.rs
- quadratic-core/src/controller/operations.rs
- quadratic-core/src/grid/sheet/rendering.rs
- quadratic-core/src/values/cellvalue.rs
- quadratic-core/src/wasm_bindings/controller/formatting.rs
- src/grid/controller/Grid.ts
- src/ui/menus/CommandPalette/ListItems/Format.tsx
- src/ui/menus/ContextMenu/FloatingContextMenu.tsx
- src/ui/menus/TopBar/SubMenus/NumberFormatMenu.tsx
> Next currency decimals

- quadratic-core/Cargo.toml
- quadratic-core/src/computation/get_cells.rs
- quadratic-core/src/grid/sheet/cells.rs
- src/web-workers/pythonWebWorker/python.ts
- src/web-workers/pythonWebWorker/run_python.py
> Next fix get cells

- quadratic-core/src/computation/get_cells.rs
- quadratic-core/src/grid/sheet/cells.rs
- src/web-workers/pythonWebWorker/python.ts
- src/web-workers/pythonWebWorker/run_python.py
> Next python 2

- quadratic-core/src/computation/get_cells.rs
- quadratic-core/src/computation/transaction_in_progress.rs
- quadratic-core/src/controller/operations.rs
- src/gridGL/UI/Cursor.ts
> Next last 2

- src/grid/sheet/Sheet.ts
- src/ui/menus/SheetBar/SheetBarTab.tsx
> sheet name properly renames on blur

- src/gridGL/interaction/CellInput.tsx
- src/gridGL/interaction/contentEditableHelper.ts
- Arrows while editing a cell will move the cell left and right if at the start or end
- Shift Tab submits and goes to cell 1 to the left, tab goes 1 to the right
> input arrow left/right moves cells

- src/ui/menus/ContextMenu/FloatingContextMenu.tsx
> FloatingContextMenu Icon Consistency

- quadratic-core/src/controller/clipboard.rs
- src/web-workers/pythonWebWorker/python.ts
> 0 properly outputs as string for python

- src/gridGL/pixiApp/thumbnail.ts
Redraws the grid lines after rendering thumbnail.
> fixes grid lines after thumbnail renders

- src/gridGL/cells/CellsFills.ts
> remove extra px

- .gitignore
- .vscode/settings.json
- package-lock.json
- package.json
- quadratic-client/package.json
- quadratic-client/src/ui/menus/TopBar/SubMenus/useBorders.ts
> Fix scripts

- quadratic-client/src/grid/controller/Grid.ts
- quadratic-client/src/gridGL/cells/CellsSheets.ts
- quadratic-client/src/gridGL/pixiApp/PixiApp.ts
> Bug column size border

- .github/workflows/coverage-rust.yml
- .vscode/settings.json
- CONTRIBUTING.md
- codecov.yaml
- package.json
- quadratic-core/examples/v1_4_simple.grid
- quadratic-core/src/grid/file/current.rs
Addresses https://github.com/quadratichq/quadratic/issues/859
> feat: Fix import bug for code cell formats

- quadratic-client/src/components/Empty.tsx
- quadratic-client/src/constants/appConstants.ts
- quadratic-client/src/constants/routes.ts
- quadratic-client/src/dashboard/ExamplesRoute.tsx
- quadratic-client/src/dashboard/FilesCreateRoute.tsx
- quadratic-client/src/dashboard/components/FilesList.tsx
- quadratic-client/src/dashboard/components/FilesListItem.tsx
Better "empty state" for users who have zero files (either because they just signed up for Quadratic or because they've deleted all their files)
Includes mixpanel events so we can track which things people click on and how often.
> feat: better zero state for empty files state

- quadratic-client/src/gridGL/QuadraticGrid.tsx
- quadratic-client/src/gridGL/interaction/pointer/PointerDown.ts
- quadratic-client/src/gridGL/pixiApp/PixiApp.ts
I do not have a mouse with a middle mouse button, so I have no idea if this worked. If not, I have a few other ideas.
Fixes #925
> Middle Mouse Drag

- quadratic-client/src/gridGL/pixiApp/PixiApp.ts
> Disable second drag plugin for mobile

- quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
> Fix crash bug on typing '=' in an empty cell

- quadratic-client/src/debugFlags.ts
- quadratic-client/src/gridGL/pixiApp/Update.ts
- quadratic-client/src/multiplayer/multiplayer.ts
Switch from raf to setInterval to hopefully increase the number of cycles given to unfocused windows
> Multiplayer interval

- quadratic-multiplayer/src/message/handle.rs
- quadratic-multiplayer/src/permissions.rs
- quadratic-multiplayer/src/server.rs
Allow anonymous users to view files.
> Mp allow anonymous access in mp

- quadratic-client/src/ui/QuadraticUI.tsx
Remove the follow box outside the hierarchy.
> Follow better box

- .vscode/settings.json
- quadratic-client/src/atoms/editorInteractionStateAtom.ts
- quadratic-client/src/debugFlags.ts
- quadratic-client/src/grid/controller/Grid.ts
- quadratic-client/src/gridGL/cells/CellsSearch.ts
- quadratic-client/src/gridGL/cells/CellsSheet.ts
- quadratic-client/src/gridGL/cells/CellsSheets.ts
- quadratic-client/src/gridGL/cells/CellsTextHash.ts
- quadratic-client/src/gridGL/interaction/keyboard/keyboardSearch.ts
- quadratic-client/src/gridGL/interaction/keyboard/useKeyboard.ts
- quadratic-client/src/gridGL/interaction/pointer/Pointer.ts
- quadratic-client/src/helpers/focusGrid.ts
- quadratic-client/src/shadcn/ui/popover.tsx
- quadratic-client/src/theme/colors.ts
- quadratic-client/src/ui/components/Search.tsx
- quadratic-client/src/ui/menus/CommandPalette/CommandPaletteListItem.tsx
- quadratic-client/src/ui/menus/CommandPalette/ListItems/Search.tsx
- quadratic-client/src/ui/menus/CommandPalette/getCommandPaletteListItems.tsx
- quadratic-client/src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
- quadratic-client/src/ui/menus/TopBar/TopBar.tsx
- quadratic-core/src/bin/export_types.rs
- quadratic-core/src/grid/mod.rs
- quadratic-core/src/grid/search.rs
- quadratic-core/src/grid/sheet.rs
- quadratic-core/src/grid/sheet/search.rs
- quadratic-core/src/wasm_bindings/controller/mod.rs
- quadratic-core/src/wasm_bindings/controller/search.rs
> Search box

- quadratic-api/src/app.ts
- quadratic-api/src/auth0/profile.ts
- quadratic-api/src/aws/s3.ts
- quadratic-api/src/email/sendEmail.ts
- quadratic-api/src/env-vars.ts
- quadratic-api/src/internal/validateM2MAuth.ts
- quadratic-api/src/middleware/validateAccessToken.ts
- quadratic-api/src/routes/ai_chat.ts
- quadratic-api/src/routes/v0/feedback.POST.ts
- quadratic-api/src/routes/v0/files.$uuid.thumbnail.POST.ts
- quadratic-api/src/routes/v0/webhooks.stripe.POST.ts
- quadratic-api/src/server.ts
- quadratic-api/src/stripe/stripe.ts
Centralize all env vars into a single file and indicate which ones are required, required for prod only, and optional.
> teams: centralize env vars

- quadratic-api/src/stripe/stripe.ts
- quadratic-client/src/routes/teams.$uuid.tsx
After a subscription is made through stripe, it redirects to the team with query params so we know to display a modal.
> Teams subscription created

- quadratic-client/src/dashboard/components/CreateTeamDialog.tsx
- quadratic-client/src/routes/teams.$uuid.tsx
Related to https://github.com/quadratichq/quadratic-website/pull/72
Before:
After:
> feat: annual/monthly team pricing

- quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
- quadratic-client/src/ui/menus/SheetBar/SheetBar.tsx
> z index for charts

- quadratic-client/src/gridGL/cells/CellsTextHash.ts
- quadratic-client/src/gridGL/cells/cellsLabel/CellLabel.ts
> Fixes overflow clipping bug (when between two cell hashes)

- quadratic-multiplayer/src/message/response.rs
> Hardcode minversion in multiplayer

- quadratic-client/.env.sentry-build-plugin
- quadratic-kernels/python-wasm/quadratic_py/utils.py
- quadratic-kernels/python-wasm/tests/test.py
> Properly cast blank in python, test to_python_type()

- quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
- quadratic-client/src/ui/menus/CodeEditor/ReturnTypeInspector.tsx
- quadratic-client/src/ui/menus/CodeEditor/snippets.ts
Added idle message to ReturnTypeInspector
> Messaging in Code Editor Updates

- quadratic-api/src/stripe/stripe.ts
> accept promotional codes at checkout

- LICENSE
- LICENSE_SHORT
> Update Agreement License

- quadratic-client/src/ui/menus/CodeEditor/AITab.tsx
- quadratic-client/src/ui/menus/CodeEditor/Console.tsx
> fix: scroll to bottom of AI panel when switching tabs

- package-lock.json
- quadratic-client/package.json
- quadratic-client/src/index.tsx
- quadratic-client/src/multiplayer/multiplayer.ts
- quadratic-client/src/multiplayer/multiplayerTypes.ts
- quadratic-multiplayer/src/error.rs
- quadratic-multiplayer/src/message/handle.rs
- quadratic-multiplayer/src/message/response.rs
- quadratic-multiplayer/src/server.rs
Closes: https://github.com/quadratichq/quadratic/issues/1269
Console errors now for multiplayer error messages sent back to the client:
> Log errors in multiplayer and the client for pubsub errors

- quadratic-client/src/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/web-workers/quadraticCore/worker/coreClient.ts
> Fix clear color in cell fills

- package-lock.json
- quadratic-client/src/app/gridGL/pixiApp/highlightedCells.ts
- quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
- quadratic-rust-client/src/jsexpr.rs
Closes https://github.com/quadratichq/quadratic/issues/1315
Also, this fixes this error in Sentry:
```
errors.ts:26 Uncaught Error: Reflect.get called on non-object
```
> Bugfix mix relative and abslute cell highlighting

- quadratic-client/src/routes/_dashboard.tsx
> Fix "Create Team" button

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> Fixes bug with expand formula button appearing for non-formulas

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
- quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsDev.ts
- quadratic-client/src/app/helpers/formulaNotation.ts
- quadratic-client/src/app/helpers/parseEditorPythonCell.ts
- quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
> fix bug with python cell references and sheet id

- quadratic-core/src/grid/sheet/bounds.rs
closes #1375
[meta_shift_select_bug.webm](https://github.com/quadratichq/quadratic/assets/54364088/badcff07-c53f-4301-b010-b17a6f631aad)
> fix: meta+shift+select is off by 1

- quadratic-client/src/app/events/events.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
> Fixes inline editor when resizing columns

- quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
> prevent submit on shift and control

- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
closes #1116 
Changes:
- Added top offset for calculation of chart resizing right.
> fix: vertical offset of chart resizing right

- quadratic-files/src/truncate.rs
This fixes the truncate test (will be merged as part of another PR)
> truncate test fix

- quadratic-api/src/routes/ai_chat.ts
- quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
gpt-4-32k is expensive and being deprecated
> use gpt-4o

- quadratic-client/src/app/helpers/files.ts
- quadratic-client/src/dashboard/components/CreateFileButton.tsx
> show file extension in import error message for unsupported type

- quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
- quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
- quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
> simple unsaved indicator in CodeEditor + disable select text around app

- quadratic-connection/.env.docker
- quadratic-connection/.env.example
- quadratic-connection/.env.test
- quadratic-connection/src/auth.rs
- quadratic-connection/src/config.rs
- quadratic-connection/src/server.rs
- quadratic-connection/src/test_util.rs
- quadratic-rust-shared/src/sql/postgres_connection.rs
**Request**: `curl --location '127.0.0.1:3003/static-ips'`
**Response**:
```json
{
"static_ips":["0.0.0.0","127.0.0.1"]
}
```
> Static ip endpoint

- quadratic-client/src/app/web-workers/quadraticCore/worker/rustConversions.ts
> fix: borders are off by 1

- quadratic-client/src/app/gridGL/pixiApp/Update.ts
> fix: update on viewport resize

- quadratic-connection/src/sql/mysql.rs
- quadratic-connection/src/sql/postgres.rs
- quadratic-rust-shared/src/quadratic_api.rs
Make connection fields optional from the API connections route
> Make password optional in connection service

- quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
- quadratic-core/src/controller/active_transactions/unsaved_transactions.rs
- quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
- quadratic-core/src/controller/operations/operation.rs
- quadratic-core/src/wasm_bindings/controller/transactions.rs
> Fix offline ResizeRow/Column and transaction ordering

- quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
- quadratic-core/src/controller/execution/control_transaction.rs
- quadratic-core/src/wasm_bindings/controller/code.rs
> Remove query stats from console and place in return type

- quadratic-connection/src/server.rs
closes https://github.com/quadratichq/quadratic/issues/1565
> Remove allowed-headers restrictions in the connection service to allow custom headers in the proxy

- quadratic-client/src/shared/components/connections/ConnectionFormMysql.tsx
- quadratic-client/src/shared/components/connections/ConnectionFormPostgres.tsx
Per [Peter's recommendation](https://quadratichq.slack.com/archives/C05E251U6P2/p1721415487505189), this implements better form labels for connections.
> fix: better form labels

- quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx
Fixes #1588 where console did not scroll when in vertical orientation
> Fixes console scroll for vertical orientation

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
> fix: position of text in inline editor wrt grid

- quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts
> fix: bug when clicking on code cells

- quadratic-client/src/app/keyboard/defaults.ts
> fix: command + Enter should not insert a second line

- quadratic-client/src/shared/api/apiClient.ts
Fixes file duplication issues.
> Fix duplication issues

- quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
- quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
- quadratic-core/src/controller/execution/execute_operation/execute_values.rs
- quadratic-core/src/controller/execution/run_code/mod.rs
Fixes: Auto row resize not applying to multiplayer.
> fix: auto row resize for multiplayer

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
> fix: multiline formula bug

- quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
- quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
- quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
ref: #1682
for merging into main after qa-wolf's test pass
> fix: inter hash text clipping

- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
> fix: precision for formula results resolving to huge numbers

- quadratic-client/src/app/gridGL/UI/UICellMoving.ts
- quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
> fix: drag to move papercuts

- quadratic-core/src/formulas/functions/tests.rs
- quadratic-core/src/values/isblank.rs
fixes clippy lint errors in local dev
> fix: lint clippy

- quadratic-client/src/app/ui/menus/TopBar/SubMenus/useBorders.ts
- quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
> fix: border formatting/styling options don't work correctly

- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCells.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
> fix: unsynced charts disappear on refresh

- quadratic-core/src/grid/sheet.rs
Fixes a bug where formula was not reading cells for code runs properly.
> Rework get_cell_for_formula

- quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
- quadratic-kernels/python-wasm/quadratic_py/run_python.py
> fix python request warning

- quadratic-core/src/controller/mod.rs
- quadratic-core/src/controller/operations/import.rs
- quadratic-core/src/controller/user_actions/code.rs
- quadratic-core/src/controller/user_actions/import.rs
- quadratic-core/src/grid/code_run.rs
- quadratic-core/src/grid/sheet.rs
This is a proper fix for #1716 plus a test to ensure this doesn't happen again
> Proper fix for formula fetching cells from grid

- quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
> fix: when resizing cursor changes to grabber when hovering over selection edge

- quadratic-client/src/app/gridGL/loadAssets.ts
fixes QA wolf error https://quadratichq.slack.com/archives/C06Q34HGV8A/p1724336225573419
adding addResourceOnce check got skipped for images used in validations PR, on merging branches
> fix: importing 2nd file without page refresh results in app error

- quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
> fix: disable command + r while in a code editor

- package-lock.json
fixes [#150](https://github.com/quadratichq/quadratic/security/dependabot/150)
> patch fast xml parser

- quadratic-client/src/app/atoms/codeHintAtom.ts
- quadratic-client/src/app/gridGL/HTMLGrid/CodeHint.tsx
> fix: update codeHint show criteria

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
> fix: text in cells not positioned properly

- quadratic-core/src/controller/operations/clipboard.rs
closes #1731 
also cleaned up all clone operations
> fix: moving formula with multi cursor incorrectly shifts formula references

- quadratic-core/src/controller/execution/run_code/run_formula.rs
- quadratic-core/src/grid/sheet/rendering.rs
- quadratic-core/src/values/array.rs
- quadratic-core/src/values/mod.rs
> Fix error reporting in formulas

- quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
- quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
- quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
- quadratic-client/src/shared/shadcn/ui/command.tsx
> fix: clicking to close code type selector loses focus

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
> fix: double-click to inline edit scrolls the sheet incorrectly

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> fix: early keystrokes are dropped when editing a cell

- quadratic-client/src/app/ui/components/FileDragDropWrapper.tsx
- quadratic-client/src/dashboard/components/FilesList.tsx
- quadratic-client/src/dashboard/components/NewFileDialog.tsx
> fix: drag n drop for moving clashes with drag n drop for import

- quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSearch.ts
- quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
- quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
- quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
> fix: move viewport event handler to QuadraticGrid component from window object

- quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
- quadratic-core/src/controller/execution/run_code/mod.rs
- quadratic-core/src/error_run.rs
closes #1767 
fixes same issue in Js & Python getCells
> fix: passing a bad sheetId params in javascript getCells puts you in an infinite loop

- quadratic-client/src/app/ui/hooks/useFileImport.tsx
- quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/dashboard/atoms/filesImportProgressAtom.ts
excel import in existing file broke while refactoring, due to incorrect argument order in `quadraticCore.importFile` function
> fix: excel import in existing file

- quadratic-client/src/app/grid/controller/Sheets.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
> fix: switching sheets creates visual bug and gets stuck in sheet

- quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
fixes: [Browser back button doesn't go back to dashboard from file but instead refreshes the file page](https://app.qawolf.com/quadratic/bug-reports/8e7e962c-a5b5-45d6-ab05-bee6548c97c6)
> fix: use replace for create file route

- quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
> fix: edit cell bug after pointer move

- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-core/src/wasm_bindings/controller/mod.rs
> fix: download file breaks ability to interact with the sheet

- quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationCheckbox.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
Fixes #1832 - bugs when changing between checkbox and dropdown lists
> fix bug with checkbox + list not properly switching

- quadratic-client/src/app/gridGL/HTMLGrid/annotations/CalendarPicker.tsx
- quadratic-client/src/app/ui/components/DateFormat.tsx
- quadratic-rust-client/src/date_time/date_time.rs
- quadratic-rust-client/src/date_time/mod.rs
> fixing date time issues

- quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
> fix: cannot go from multi-cell selection to single-cell selection

- quadratic-core/src/controller/active_transactions/pending_transaction.rs
- quadratic-core/src/controller/execution/run_code/mod.rs
setting code cell has 2 operations:
- SetCellValues
- ComputeCode
`updateCodeCell` message is sent in `finalize_code_run`, code_string is part of this message
on undo, this happens in reverse, so when `updateCodeCell` message is sent, code_string is not updated, so old code string is being sent.
I am using the new `add_code_cell` function implemented in https://github.com/quadratichq/quadratic/pull/1861 which sends `updateCodeCell` in `finalize_transaction`, so at this point all undo operations are complete and `updateCodeCell` message will be correct
> fix: update code cell on undo / redo

- quadratic-kernels/python-wasm/quadratic_py/utils.py
I forgot to push this before merging #1871 🤦
> Remove print statement

- quadratic-client/src/app/ui/components/BorderMenu.tsx
- quadratic-client/src/shared/components/Icons.tsx
- Fix icon for top border (Fixes [QA wolf bug](https://quadratichq.slack.com/archives/C06Q34HGV8A/p1726943985715559))
- Add tooltips to buttons
> fix: border menu

- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
> fix: chart(python) resizing off by a lot of pixels

- quadratic-core/src/formulas/functions/lookup.rs
- quadratic-core/src/values/convert.rs
> Fix Match formula

- quadratic-client/src/shared/shadcn/ui/menubar.tsx
> fix: esc on file menu will refocus grid

- quadratic-client/src/app/grid/actions/openCodeEditor.ts
- quadratic-client/src/app/gridGL/cells/CellsArray.ts
> fix: toggle code editor

- quadratic-client/src/app/gridGL/Events.tsx
- quadratic-client/src/app/ui/menus/Toolbar/CursorPosition.tsx
- quadratic-client/src/app/ui/menus/Toolbar/FormattingBar.tsx
- quadratic-client/src/shared/shadcn/ui/command.tsx
- quadratic-client/src/shared/shadcn/ui/dialog.tsx
- quadratic-client/src/shared/shadcn/ui/popover.tsx
> fix: pressing the shift key closes the goto menu and custom date time input box

- quadratic-client/src/app/events/events.ts
- quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/tablesOverlay/TablesOverlay.tsx
- quadratic-client/src/app/gridGL/cells/CellsArray.ts
- quadratic-client/src/app/gridGL/helpers/intersects.ts
- quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
- quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts
- quadratic-client/src/app/quadratic-core-types/index.d.ts
- quadratic-core/src/grid/js_types.rs
- quadratic-core/src/grid/sheet/rendering.rs
- quadratic-rust-shared/src/auto_gen_path.rs
> table name

- quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
- quadratic-client/src/shared/utils/isLinux.ts
ref https://github.com/quadratichq/quadratic/issues/1965
> fix: prevent default paste on middle click in Linux

- quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
- quadratic-client/src/routes/file.$uuid.tsx
fixes - https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1728742217446569
> fix: offline sync fieId

- quadratic-client/src/app/gridGL/cells/borders/Borders.ts
fixes https://quadratichq.slack.com/archives/C06Q34HGV8A/p1728580316161059
> fix(QA Wolf): Border formatting is not working as expected

- quadratic-client/src/app/ui/components/ImportSettings.tsx
- quadratic-client/src/dashboard/components/ImportProgressList.tsx
Minor UI improvements to the CSV delimiter, including using existing UI dialogs instead of custom ones
> jim: csv delimiter tweaks

- quadratic-core/src/controller/execution/spills.rs
file: [Untitled.zip](https://github.com/user-attachments/files/17480414/Untitled.zip)
before:
https://github.com/user-attachments/assets/e2cf3d06-03af-40d5-89e8-a47ff60d62df
after:
https://github.com/user-attachments/assets/cb1de4cf-95eb-4447-8d26-59e397ab2511
> fix: dirty_hashes for change_spill

- quadratic-client/src/app/gridGL/cells/CellsArray.ts
> fix: error triangle doesn't disappear immediately when cell contents are deleted

- quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/EditMenubarMenu.tsx
- quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/MenubarItemAction.tsx
- quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/TopBarMenus.tsx
- quadratic-client/src/shared/shadcn/ui/menubar.tsx
closes https://github.com/quadratichq/quadratic/issues/1997
closes https://github.com/quadratichq/quadratic/issues/2020
> fix: goto button in edit menu and mouse hover on all menus

- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
> fix: grid lines don't render for cut off text when they should

- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashSpecial.ts
> fix: data validations don't remained centered in correct column

- quadratic-client/src/app/events/events.ts
- quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/annotations/Annotations.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/validations/useHtmlValidations.ts
- quadratic-client/src/app/gridGL/UI/UICellImages.ts
- quadratic-client/src/app/gridGL/UI/UIValidations.ts
- quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
- quadratic-client/src/app/gridGL/cells/CellsFills.ts
- quadratic-client/src/app/gridGL/cells/CellsSearch.ts
- quadratic-client/src/app/gridGL/cells/CellsSheet.ts
- quadratic-client/src/app/gridGL/cells/CellsSheets.ts
- quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
- quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
- quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
- quadratic-client/src/app/ui/components/CursorSelectionDisplay.tsx
- quadratic-client/src/app/ui/icons/index.tsx
- quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
- quadratic-client/src/app/ui/menus/BottomBar/SelectionSummary.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
- quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
- quadratic-client/src/app/ui/menus/Toolbar/CursorPosition.tsx
- quadratic-client/src/app/ui/menus/Validations/Validation/ValidationHeader.tsx
- quadratic-client/src/app/ui/menus/Validations/Validations/ValidationEntry.tsx
- quadratic-client/src/app/ui/menus/Validations/Validations/Validations.tsx
- quadratic-client/src/app/ui/menus/Validations/Validations/ValidationsHeader.tsx
- quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.test.ts
- quadratic-client/src/shared/shadcn/ui/tooltip.tsx
> fix: app slowdown

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
> fix: tab key sometimes inserts 2 spaces

- quadratic-client/src/app/ui/components/Following.tsx
> fix: unfollowing from the grid doesn't work

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
- quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
> fix: jumping in the sheet when clicking into cells

- quadratic-client/src/dashboard/components/DashboardSidebar.tsx
- quadratic-client/src/dashboard/components/FilesListEmptyState.tsx
- quadratic-client/src/dashboard/components/NewFileButton.tsx
Fixes back button when creating a new file, [Fixes QA wolf issue #43](https://app.qawolf.com/quadratic/bug-reports/d21b18cd-61a7-47ca-a8d3-45b5394605cf)
> fix: back button when creating a new file

- quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx
Prompted by a user who didn't understand what to put for account identifier.
> Account identifier clarity

- quadratic-client/src/app/atoms/aiAnalystAtom.ts
- quadratic-client/src/app/atoms/gridSettingsAtom.ts
- quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/ViewMenubarMenu.tsx
Allows users to control whether the AI panel shows up. Removes the > 3 closed check.
> Add View Option: "Show AI on startup" (default = true)

- Cargo.lock
- package-lock.json
- quadratic-connection/src/server.rs
> fix: proxy calls are cached

- Cargo.lock
- package-lock.json
- quadratic-core/src/a1/a1_selection/a1_selection_select.rs
> fix: right-click column select doesn't work on multi-column selection

- Cargo.lock
- package.json
- quadratic-files/src/file.rs
- quadratic-files/src/server.rs
- quadratic-files/src/state/stats.rs
- quadratic-files/src/test_util.rs
- quadratic-files/src/truncate.rs
- quadratic-rust-shared/src/sql/mysql_connection.rs
http://127.0.0.1:3002/stats
```
{
"last_processed_file_time": "2025-01-17T23:32:25.102747+00:00",
"last_processed_file_elapsed": "7 seconds ago",
"files_to_process_in_pubsub": 20,
"last_processed_transaction_time": "2025-01-17T23:32:25.102747+00:00",
"last_processed_transaction_elapsed": "7 seconds ago",
"channels_to_truncate_in_pubsub": 2
}
```
> Add stats endpoint to the files service

- quadratic-client/src/app/helpers/downloadFileInBrowser.ts
- quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
Added a `cleanup` function to handle js worker termination and object URL revocation. prevents resource leaks.
> revokeObjectUrl

- quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
fixes: https://quadratichq.slack.com/archives/C06Q34HGV8A/p1737644462643649
> fix: qa wolf - Code Chat AI Prompt Error

- package-lock.json
- quadratic-api/package.json
- quadratic-api/src/ai/handler/anthropic.ts
- quadratic-api/src/ai/handler/bedrock.ts
- quadratic-api/src/ai/handler/openai.ts
- quadratic-api/src/ai/helpers/anthropic.helper.ts
- quadratic-api/src/ai/helpers/bedrock.helper.ts
- quadratic-api/src/ai/helpers/openai.helper.ts
- quadratic-api/src/routes/v0/ai.chat.POST.test.ts
- quadratic-api/src/routes/v0/ai.chat.POST.ts
- quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
- quadratic-client/src/app/ai/hooks/useAIModel.tsx
- quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
- quadratic-client/src/app/ai/hooks/useGetChatName.tsx
- quadratic-client/src/app/ai/offline/aiAnalystChats.test.ts
- quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
- quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
- quadratic-client/src/app/ui/menus/Validations/Validation/useValidationData.ts
- quadratic-shared/ai/helpers/model.helper.ts
- quadratic-shared/ai/models/AI_MODELS.ts
- quadratic-shared/typesAndSchemasAI.ts
Checklist:
- Old chat history should work, even with new models
- Hot swapping of models should work in between chat
> feat: add 3.7 sonnet

- quadratic-client/Dockerfile
- quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
- quadratic-core/src/formulas/parser/mod.rs
> fix doctests

- quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenu.tsx
Fixes https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1740617319494609
> fix: correct context menu for JS charts

- quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
- quadratic-client/src/app/gridGL/cells/tables/Table.ts
- quadratic-client/src/app/ui/QuadraticSidebar.tsx
- quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/AIThinkingBlock.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/AddDataTable.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/SetCellValues.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/SetCodeCellValue.tsx
- quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/ToolCard.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
- quadratic-client/src/shared/components/Icons.tsx
Changes listed in commit names
> Minor UI Changes

- quadratic-core/src/grid/file/v1_7_1/upgrade.rs
> Show column headers for connection upgrades

- quadratic-core/src/a1/a1_context/table_map.rs
- quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
- quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
- quadratic-core/src/controller/execution/run_code/mod.rs
- quadratic-core/src/controller/operations/autocomplete.rs
- quadratic-core/src/controller/operations/clipboard.rs
- quadratic-core/src/controller/operations/data_table.rs
- quadratic-core/src/controller/operations/import.rs
- quadratic-core/src/grid/data_table/mod.rs
- quadratic-shared/ai/models/AI_MODELS.ts
> fix: table name update on duplicate sheet

- .github/workflows/production-bump-version.yml
- quadratic-core/src/grid/sheet/a1_context.rs
Merge pull request #2240 from quadratichq/qa
> QA: Feb 27 - Tables Followup Target Shipping Monday Afternoon

- quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
Fixes this bug:
https://github.com/user-attachments/assets/744c2f3e-af65-46dc-ae3b-87a3df643327
> Fix floating column headers height

- quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
- quadratic-core/src/controller/operations/sheets.rs
pending item from https://github.com/quadratichq/quadratic/pull/2339
this pr updates sheet name in cell ref of the new duplicate sheet
> fix: update sheet name in cell ref on duplicate sheet

- quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
> Fixes resizing grid column when mouse moves over table UI

- quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Fixes https://github.com/quadratichq/quadratic/issues/2398
> Fix phantom click

- quadratic-client/src/app/gridGL/UI/UICopy.ts
- quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
> Fixes marching ants luminosity

- quadratic-client/src/app/gridGL/cells/tables/TableColumnHeader.ts
- quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
- quadratic-client/src/app/gridGL/cells/tables/Tables.ts
> Ensure table is not highlighted after copy as PNG on table column

- quadratic-client/src/dashboard/components/BrowserCompatibilityLayoutRoute.tsx
- quadratic-client/src/dashboard/components/Empty.tsx
- quadratic-client/src/index.tsx
- quadratic-client/src/routes/_dashboard.tsx
- quadratic-client/src/routes/_root.tsx
- quadratic-client/src/routes/file.$uuid.tsx
- quadratic-client/src/routes/files.shared-with-me.tsx
- quadratic-client/src/routes/teams.$teamUuid.files.private.tsx
- quadratic-client/src/routes/teams.$teamUuid.tsx
> better capture sentry errors

- quadratic-client/src/app/atoms/contextMenuAtom.ts
- quadratic-client/src/app/events/events.ts
- quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/tableSort/TableSort.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/cells/tables/Tables.ts
- quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
closes #2418 
fixes the linked issue
no
no
> fix: table sort menu doesn't work when it is selected while cell is highlighted

- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
closes #2230 
fixes the linked issue
no
no
> fix: - should go before $

- quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
- quadratic-core/src/controller/execution/execute_operation/mod.rs
- quadratic-core/src/controller/user_actions/data_table.rs
closes #2454
fixes https://github.com/quadratichq/quadratic/pull/2427#issuecomment-2712040005
Fixes AddDataTable op - rendering and undo
No
No
> fix: AddDataTable and GridToDataTable op

- quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
Re-enable single-finger mobile drag
> Single finger mobile drag

- .github/workflows/qa-deploy.yml
[insert link(s) here]
This should sufficiently describe the functionality added/improved in the PR. 
E.g. "this changes the core functionality of tables, all the basic table functionality should be validated to be working as expected."
E.g. "@xyzperson need docs link to security page for link in-app"
> fix: matrix build

- .github/workflows/qa-deploy.yml
[insert link(s) here]
This should sufficiently describe the functionality added/improved in the PR. 
E.g. "this changes the core functionality of tables, all the basic table functionality should be validated to be working as expected."
E.g. "@xyzperson need docs link to security page for link in-app"
> fix: matri build again

- quadratic-connection/package.json
- quadratic-files/package.json
- quadratic-multiplayer/package.json
- quadratic-multiplayer/src/server.rs
- quadratic-rust-shared/package.json
Fixes https://github.com/quadratichq/quadratic/issues/2343
There was an intermittent test timing out in CI in multiplayer.  I added code to attempt to avoid a race condition, as well as added a timer to quit the test after 3 seconds to avoid holding up CI.
> Fix intermittent multiplayer test timeout

- quadratic-client/src/dashboard/components/DashboardSidebar.tsx
- quadratic-client/src/routes/teams.$teamUuid.settings.tsx
Team Owner
- Can see "Upgrade to pro" in side bar, then settings looks like this:
Team Editor
- Can see "Upgrade to pro" in side bar, then settings looks like this:
> Billing Settings for Non Team Owner

- infra/package-lock.json
fixes pulumi deployment
https://github.com/quadratichq/quadratic/actions/runs/13934786771/job/39000454534
> fix: update pulumi lock file

- quadratic-core/src/grid/contiguous/contiguous_2d.rs
Contiguous2D now has nice debug formatting.
```
Contiguous2D(
ContiguousBlocks(
{
1: (1..3, ContiguousBlocks({1: (1..3, None), 3: (3..5, Some(Some(true))), 5: (5.., None)})),
3: (3.., ContiguousBlocks({1: (1.., None)})),
},
),
),
```
```
columns A:B (1..=2)
A1:B2       None
A3:B4       Some(Some(true))
A5:B        None
columns C: (3..)
C:          None
```
> Improve debug formatting for `Contiguous2D`

- quadratic-core/src/grid/sheet/col_row/column.rs
- quadratic-core/src/grid/sheet/col_row/row.rs
Rendering bug with deleting columns and fills:
https://github.com/user-attachments/assets/4606f5d4-3e4c-42f8-ba01-b8f556beb259
https://github.com/user-attachments/assets/a3a3b916-7ee5-4357-9f07-bca93ad17d82
> fixes a bug with delete col/row and fills

- quadratic-core/src/grid/contiguous/contiguous_2d.rs
- quadratic-core/src/grid/contiguous/contiguous_blocks.rs
These are utility functions with their own unit tests. No user testing needed.
> Add `is_all_default_in_range()` and `unique_values_in_range()` for `Contiguous2D`

- Cargo.lock
- package-lock.json
- quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
fixes https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1743011543667839
> fix: running py transactionId

- quadratic-core/src/wasm_bindings/controller/code.rs
https://quadratichq.slack.com/archives/C05E251U6P2/p1743173262476549
> Remove panic from setCodeCell (merge to main)

- quadratic-core/src/controller/execution/control_transaction.rs
- quadratic-core/src/controller/execution/receive_multiplayer.rs
- quadratic-core/src/controller/user_actions/import.rs
- quadratic-core/src/wasm_bindings/controller/import.rs
Fixes no rendering (un-finished transaction) on excel import in app
> fix: render on excel import

- quadratic-api/src/ai/docs/PythonDocs.ts
Matplotlib attempts are emerging in a very small (but meaningful) amount of charting attempts. Little extra armor against this emerging attempt by AI. It's not surprising as most common library but it should never happen. 
Anecdotal: in a 6 hour session of 100+ charting attempts, this expressed itself about 5 times.
> Matplotlib attempts are emerging from AI

- quadratic-core/src/bin/docgen.rs
- quadratic-core/src/bin/docs_end.md
- quadratic-core/src/formulas/functions/macros.rs
- Update criteria and wildcard links
- Add paragraph to the end that links to the list of in-progress fns
No user-facing changes. Code changes are trivial.
> Improve formula functions docs output

- quadratic-client/src/shared/components/Empty.tsx
> chore: capture error in mixpanel

- quadratic-shared/ai/models/AI_MODELS.ts
- quadratic-shared/typesAndSchemasAI.ts
> chore: switch to gemini 2.5 pro preview

- .github/pull_request_template.md
Adds a section for QA Wolf to PR template. Please note in that section if you think a QA Wolf test can/should be created to accompany your PR.
> Add QA Wolf to PR template

- quadratic-core/src/controller/operations/cell_value.rs
- quadratic-core/src/controller/user_actions/import.rs
- quadratic-core/src/values/cellvalue.rs
> fix: parsing of numbers with parentheses and/or spaces

- quadratic-api/src/ai/docs/PythonDocs.ts
- quadratic-api/src/ai/docs/QuadraticDocs.ts
- quadratic-shared/ai/specs/aiToolsSpec.ts
This docs update changes docs in three places: 
**Quadratic docs:** tiny change to emphasize minimal verbosity in responses (this is already stated elsewhere but this small change in docs seems to emphasize it and cut responses in many cases). 
**Python docs:** large changes to Python docs that fixes some formatting to be more consistent, improves some prompting techniques for explicit description to AI, and adds a handful of examples for common use-cases of Quadratic so AI knows what to try first to be successful and what success looks like. 
Also, AI was sharing code for plots in chat nearly every time it tried to make a chart. Won't do this anymore. 
**ToolsSpec:** reinforcement to not put code in chat, been doing that a lot lately.
- User vibe check: wouldn't hurt for reviewers to …
> AI docs update

- quadratic-api/jest.setup.js
- quadratic-api/src/routes/v0/teams.$uuid.GET.ts
- quadratic-api/src/stripe/stripe.ts
- quadratic-client/src/routes/teams.$teamUuid.settings.tsx
ref: https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1744052327442469
- Fixes manage billing button not showing
- Sync db every time with stripe on team.GET request, instead of once in 24 hrs
> fix: manage billing button and stripe db sync

- quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
fixes persistent red dot on the kernel menu, and rendering issue, after connection code execution is cancelled
> fix: finalize transaction on cancel connection

- quadratic-multiplayer/src/server.rs
disables flaky mp test `user_is_idle_in_a_room_get_removed_and_reconnect`
> fix: disable flaky multiplayer test

- quadratic-client/index.html
- quadratic-client/src/app/ui/QuadraticUI.tsx
- quadratic-client/src/router.tsx
- quadratic-client/src/routes/_dashboard.tsx
- quadratic-client/src/routes/_root.tsx
- quadratic-client/src/routes/file.$uuid.duplicate.tsx
- quadratic-client/src/routes/file.$uuid.history.tsx
- quadratic-client/src/shared/components/Empty.tsx
- quadratic-client/src/shared/hooks/useRemoveInitialLoadingUI.ts
Fixes [an issue](https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1744810749412499) where, if you signed up for the 1st time and came into the app, the loading screen was still showing (fixed upon refresh).
- Sign up as a new user
- Loading screen should disappear when you come into the app
Also, any subsequent reloads of the app as a logged-in user should also remove the loading screen once the app loads.
> fix: loading screen

- quadratic-client/src/app/gridGL/interaction/pointer/PointerAutoComplete.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
> fix: enable mouse edges for autocomplete

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
> fix: clicking sheet references across sheets doesn't get saved

- .github/workflows/production-deploy.yml
- .github/workflows/qa-deploy.yml
- Procfile
- quadratic-api/src/app.ts
fixes concurrency of verify version ci job, where each service needs its own concurrency group
> fix: verify version concurrency

- .github/workflows/preview-build-deploy-images.yml
- .github/workflows/production-deploy.yml
- .github/workflows/qa-deploy.yml
- Procfile
Fixes api version env variable in heroku
> fix: api version on health endpoint

- .github/workflows/preview-build-deploy-images.yml
- .github/workflows/production-deploy.yml
- .github/workflows/qa-deploy.yml
adds missing backslash to the curl command
> fix: add missing backslash

- quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
> fix: code cell position for "Use Connection"

- quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
- quadratic-client/src/shared/components/ABTest.tsx
The event was sending every time `delaySeconds` updates
> Fix mixpanel event

- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorStyles.scss
- quadratic-client/src/app/gridGL/UI/Cursor.ts
> fix: text align in inline monaco

- .github/workflows/production-github-release.yml
Adds github workflow for generating release and tag on merging into main
> chore: add github release in ci

- package-lock.json
- quadratic-client/package.json
- quadratic-client/vite.config.js
Fixes source map upload to sentry, env variables were not being correctly read in vite.config
> fix: sentry source map upload

- quadratic-client/src/app/ai/hooks/useAIModel.tsx
- quadratic-shared/ai/models/AI_MODELS.ts
- change ai default to thinking off
- fix think toggle state on update
> chore: change ai default, fix thinking state on update

- quadratic-core/src/grid/file/v1_8/upgrade.rs
fixes https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1745623582595389?thread_ts=1745621247.940899&cid=C03VC0Q1MPA
> fix: 1.8 show column migration

- quadratic-client/src/app/actions/helpActionsSpec.ts
- quadratic-client/src/dashboard/components/DashboardSidebar.tsx
- quadratic-client/src/shared/constants/urls.ts
> feat: add forum link

- quadratic-client/src/app/ai/tools/aiToolsActions.ts
- quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
- quadratic-client/src/app/ui/components/FixSpillError.tsx
- quadratic-shared/ai/specs/aiToolsSpec.ts
> ai uses the current sheet when request was made

- dev/cli.js
- dev/cli.ts
- dev/constants.js
- dev/constants.ts
- dev/control.js
- dev/control.ts
- dev/help.js
- dev/help.ts
- dev/input.js
- dev/input.ts
- dev/ui.js
- dev/ui.ts
- package-lock.json
- package.json
- quadratic-files/Cargo.lock
- quadratic-multiplayer/Cargo.lock
- quadratic-shared/package.json
`node dev` now has a watcher for quadratic-shared (node dev -s or press `s` key while running)
> Add quadratic-shared watcher to node dev

- quadratic-api/src/ai/docs/PythonDocs.ts
AI keeps trying to recompute cells with dependencies when it updates the data; this should reduce the frequency of that behavior.
> AI keeps trying to recompute cells with dependencies when it updates the data 

- quadratic-client/src/app/gridGL/UI/Cursor.ts
- quadratic-client/src/app/gridGL/cells/tables/Tables.ts
> Hide cursor on full table selection

- quadratic-api/src/routes/v0/internal.user.$auth0Id.teams.$uuid.GET.ts
Decrypts keys for the get_team route in api
> Decrypt team

- quadratic-core/src/grid/data_table/display_value.rs
- quadratic-core/src/test_util/create_code_table.rs
- quadratic-core/src/values/array.rs
- quadratic-files/Cargo.lock
Fixes #2881 
Flattening a one-cell formula should not crash core.
> Fix bug with flattening one-cell formula

- .github/workflows/ci.yml
- .github/workflows/production-deploy.yml
- .github/workflows/qa-deploy.yml
- quadratic-core/Cargo.toml
- quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
- quadratic-core/src/controller/formula.rs
- quadratic-core/src/grid/file/v1_7_1/sheet_offsets/mod.rs
- quadratic-core/src/grid/formats/sheet_format_updates.rs
- quadratic-core/src/grid/sheet.rs
- quadratic-core/src/grid/sheet/cell_array.rs
- quadratic-core/src/grid/sheet/validations/rules/validation_date_time.rs
- quadratic-core/src/grid/sheet/validations/rules/validation_number.rs
fixes pulumi deploy for qa / prod
ref: https://github.com/quadratichq/quadratic/actions/runs/15029349083/job/42238847139
> fix: qa / prod ci deployment

- quadratic-core/src/controller/transaction.rs
- quadratic-multiplayer/src/message/handle.rs
> More mp tests and logs

- quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
- quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
- quadratic-core/src/a1/a1_selection/query.rs
- quadratic-core/src/controller/execution/execute_operation/execute_validation.rs
- quadratic-core/src/controller/execution/run_code/get_cells.rs
- quadratic-core/src/controller/export.rs
- quadratic-core/src/controller/operations/cell_value.rs
- quadratic-core/src/controller/operations/csv.rs
- quadratic-core/src/formulas/ast.rs
- quadratic-core/src/formulas/ctx.rs
- quadratic-core/src/formulas/functions/lookup.rs
- quadratic-core/src/grid/sheet.rs
- quadratic-core/src/grid/sheet/a1_selection.rs
- quadratic-core/src/grid/sheet/ai_context.rs
- quadratic-core/src/grid/sheet/bounds/mod.rs
- quadratic-core/src/grid/sheet/clipboard.rs
- quadratic-core/src/grid/sheet/summarize.rs
- quadratic-core/src/grid/sheet/validations/rules/validation_list.rs
- quadratic-core/src/wasm_bindings/controller/bounds.rs
fixes: https://quadratichq.slack.com/archives/C05E251U6P2/p1748454937208539
also cleanup of unused bounds wasm functions
> fix: infinite formatting bounds handling in selection, core stuck

- quadratic-client/src/app/gridGL/cells/tables/TableName.ts
Fixes positioning of modified date when resizing cells.
> Fix positioning of table's modified date

- quadratic-api/src/ai/docs/QuadraticDocs.ts
- quadratic-api/src/ai/helpers/context.helper.ts
- quadratic-shared/ai/specs/aiToolsSpec.ts
- With our new model choices, they are default significantly verbose than prior model choice. 
- Some models are struggling with when to use get cells 
This PR ensures better behavior in both of the above ^
> AI prompt improvements 

- quadratic-api/src/ai/handler/ai.handler.ts
- quadratic-api/src/ai/helpers/anthropic.helper.ts
- quadratic-api/src/ai/helpers/bedrock.helper.ts
- quadratic-api/src/ai/helpers/openai.helper.ts
- quadratic-api/src/ai/helpers/vertexai.helper.ts
[insert link(s) here]
This should sufficiently describe the functionality added/improved in the PR. 
E.g. "this changes the core functionality of tables, all the basic table functionality should be validated to be working as expected."
Please notify here if you'd like a test created in QA Wolf to accompany this PR.
E.g. "@xyzperson need docs link to security page for link in-app"
> fix: remove console error for extra ai response content

- quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
Track what people are clicking in this
> chore: mixpanel event for empty grid message widget

- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCellResizing.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerImages.ts
- quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
- quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
- quadratic-core/src/controller/execution/run_code/mod.rs
- quadratic-core/src/controller/operations/cell_value.rs
- quadratic-core/src/controller/operations/clipboard.rs
- quadratic-core/src/wasm_bindings/controller/formatting.rs
https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1749393603640909
Also improves how sizing works, so if you resize a chart, and then have an error, when you fix the error, the chart will return to its resized size.
> Fix chart size bug

- quadratic-shared/ai/helpers/message.helper.ts
- quadratic-shared/ai/specs/aiToolsSpec.ts
Cleans up AI messages older than 3 (instead of 1)
> Less aggressive clean up for AI

- quadratic-client/src/app/debugFlags/debugFlagsDefinitions.ts
- quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
- quadratic-client/src/app/ui/menus/BottomBar/Coordinates.tsx
Adds a debug option to show window coordinates in the footer. This is useful for creating e2e tests.
> Adds debug option to show viewport coordinates

- quadratic-api/src/ai/helpers/modelRouter.helper.ts
- quadratic-shared/ai/specs/aiToolsSpec.ts
> Revert router 

- quadratic-api/src/ai/handler/ai.handler.ts
- quadratic-api/src/ai/helpers/context.helper.ts
- quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
- quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
- quadratic-shared/typesAndSchemasAI.ts
This improves: 
When creating sample data the AI often uses stale data based on its training. 
When creating code with date ranges the AI often produces stale ranges
> Current date in context 

- quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
- test/e2e/src/spreadsheetComputation.spec.ts
Changes where cursor goes after pressing tab when completing auto suggestion:
Old behavior:
https://github.com/user-attachments/assets/5a5fcaef-3de1-4051-aae6-eeaf1845c12b
New behavvior:
https://github.com/user-attachments/assets/965afde5-2223-440a-a43d-0a425adc2cdd
> Pressing tab on suggestion list moves right instead of down

- quadratic-client/src/app/gridGL/cells/tables/Tables.ts
- quadratic-client/src/app/gridGL/cells/tables/TablesCache.ts
- quadratic-core/src/controller/send_render.rs
https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1751402689509509
When moving tables, the table would sometimes lose highlight.
> Fix bug with moving table and highlighting table

- quadratic-client/src/app/gridGL/UI/HtmlPlaceholders.ts
- quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
- quadratic-client/src/app/gridGL/pixiApp/copyAsPNG.ts
- quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
fixes: https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1751315282492489
> fix: copyAsPng bug

- quadratic-core/src/controller/send_render.rs
> fix: arrow keys in new sheet

- quadratic-client/src/app/ui/QuadraticAppDebugSettings.tsx
Allows debugging menu to properly scroll.
> Adds `flex` to debugging menu

- quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
https://github.com/user-attachments/assets/d8f68f07-205f-4f1f-86b1-2ed6b4081cb3
https://github.com/user-attachments/assets/1633fa20-18e5-46fc-906e-a848e092945b
> Fixes subtle bug with autocomplete

- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
- quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
- quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
- quadratic-core/src/wasm_bindings/controller/render.rs
- quadratic-rust-shared/Cargo.toml
Fixed an expected error crashing the app.
> Fix core error after getRenderCells

- quadratic-client/src/app/events/events.ts
- quadratic-client/src/app/grid/controller/Sheets.ts
- quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
- quadratic-client/src/app/gridGL/HTMLGrid/validations/useHtmlValidations.ts
- quadratic-client/src/app/gridGL/UI/UISingleCellOutlines.ts
- quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
- quadratic-client/src/app/gridGL/cells/Borders.ts
- quadratic-client/src/app/gridGL/cells/CellsArray.ts
- quadratic-client/src/app/gridGL/cells/CellsFills.ts
- quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
- quadratic-client/src/app/gridGL/cells/tables/Tables.ts
> fix: auto resize doesn't apply correctly to chart

- quadratic-core/src/controller/user_actions/formats.rs
- quadratic-core/src/grid/sheet/format_summary.rs
- quadratic-core/src/wasm_bindings/controller/formatting.rs
> fix format summary behind tables

- quadratic-core/src/a1/a1_selection/intersects.rs
- quadratic-core/src/a1/table_ref/query.rs
- quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
- quadratic-core/src/controller/operations/cell_value.rs
- quadratic-core/src/controller/operations/clipboard.rs
- quadratic-core/src/controller/operations/code_cell.rs
- quadratic-core/src/controller/operations/data_table.rs
- quadratic-core/src/controller/user_actions/clipboard.rs
- quadratic-core/src/grid/data_table/column.rs
- quadratic-core/src/grid/data_table/column_header.rs
- quadratic-core/src/grid/data_table/fix_names.rs
- quadratic-core/src/grid/data_table/mod.rs
> fix: can't copy table column data to another table column

- quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
> fix: drag and drop AI Chat image/pdf indicator persists

- quadratic-core/src/a1/table_ref/query.rs
> fix: table selection highlighting bug

- quadratic-client/src/app/gridGL/cells/tables/Table.ts
> fix: when deleting many table rows, header UI persists at bottom of table

- quadratic-core/src/controller/operations/clipboard.rs
> fix: when pasting values only for an entire table, convert multi-line cell values to space separated ones

- quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
fixes: https://quadratichq.slack.com/archives/C06Q34HGV8A/p1754437330777889
> fix: offline syncing state

- quadratic-shared/ai/specs/aiToolsSpec.ts
fixes: https://quadratichq.slack.com/archives/C06Q34HGV8A/p1754523252262619?thread_ts=1754523238.286859&cid=C06Q34HGV8A
> fix: auto correct ai args types

- quadratic-client/src/routes/teams.$teamUuid.members.tsx
- quadratic-client/src/shared/components/ShareDialog.tsx
Alert users in members page that adding members while on Pro costs per seat. 
Notification should not show for free teams. Should show for paid teams.
> Alert users in members page that adding members while on Pro costs per seat 

- quadratic-client/src/app/ai/toolCards/AddDateTimeValidation.tsx
- quadratic-client/src/app/ai/toolCards/AddListValidation.tsx
- quadratic-client/src/app/ai/toolCards/AddLogicalValidations.tsx
- quadratic-client/src/app/ai/toolCards/AddMessage.tsx
- quadratic-client/src/app/ai/toolCards/AddNumberValidation.tsx
- quadratic-client/src/app/ai/toolCards/AddTextValidation.tsx
- quadratic-client/src/app/ai/toolCards/ColorSheets.tsx
- quadratic-client/src/app/ai/toolCards/ConvertToTable.tsx
- quadratic-client/src/app/ai/toolCards/CreateNewSheet.tsx
- quadratic-client/src/app/ai/toolCards/DeleteCells.tsx
- quadratic-client/src/app/ai/toolCards/DeleteColumns.tsx
- quadratic-client/src/app/ai/toolCards/DeleteRows.tsx
- quadratic-client/src/app/ai/toolCards/DeleteSheet.tsx
- quadratic-client/src/app/ai/toolCards/DuplicateSheet.tsx
- quadratic-client/src/app/ai/toolCards/InsertColumns.tsx
- quadratic-client/src/app/ai/toolCards/InsertRows.tsx
- quadratic-client/src/app/ai/toolCards/MoveCells.tsx
- quadratic-client/src/app/ai/toolCards/MoveSheet.tsx
- quadratic-client/src/app/ai/toolCards/RemoveValidations.tsx
- quadratic-client/src/app/ai/toolCards/RenameSheet.tsx
- quadratic-client/src/app/ai/toolCards/RerunCode.tsx
- quadratic-client/src/app/ai/toolCards/ResizeColumns.tsx
- quadratic-client/src/app/ai/toolCards/ResizeRows.tsx
- quadratic-client/src/app/ai/toolCards/SetBorders.tsx
- quadratic-client/src/app/ai/toolCards/SetTextFormats.tsx
ref: https://github.com/quadratichq/quadratic/pull/3375
> fix: tool card text length

- quadratic-shared/ai/specs/aiToolsSpec.ts
Tool descriptions were very short and not clear. 
AI struggling to know when to call get code cell value. Proper behavior with this would be essential if we are going to try to retire the right chat.
> Tool description improvements for getcodecellvalue and resize rows

- quadratic-client/src/app/grid/sheet/SheetCursor.ts
- quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
- test/e2e/src/spreadsheetKeyboard.spec.ts
- test/e2e/src/spreadsheetMouse.spec.ts
> Clicking top-left corner of canvas properly selects all (again)

- quadratic-client/src/routes/file.$uuid.tsx
- quadratic-client/src/shared/constants/routes.ts
fixes - https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1757370077443469?thread_ts=1757356666.602109&cid=C03VC0Q1MPA
> fix: login redirect to file url

- .github/workflows/production-deploy.yml
- .github/workflows/qa-deploy.yml
- docker/client/config/default.conf
- quadratic-client/src/app/gridGL/loadAssets.ts
use cache control headers from cdn or nginx
> fix: cleanup cache changes

- quadratic-api/src/ai/docs/PythonDocs.ts
> Discourage multiple charts in one cell 

- quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
fixes: https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1758156019790849
> fix: characterSize undefined in GridHeadings

- DEVELOPMENT.md
- PLAYBOOK.md
> Create playbook with deploying and modifying environment variables

- quadratic-api/src/auth/providers/workos.ts
- quadratic-client/src/auth/workos.ts
> Attempted fix for localhost auth errors
