quadratichq/quadratic

src/core/gridGL/graphics/ViewportComponent.tsx
src/core/gridGL/graphics/drawAxesLines.ts
src/core/gridGL/graphics/drawGridLines.ts

I'll work on the props.showGridAxes in a separate branch.

separate out axisLines from gridLines

---

src/core/computations/python/run_python.py

Hi! This looks like a great project. I just had a play with the demo and noticed a couple of things that I thought should be fixed.
1. The `first_row_header` argument mentioned in the [docs](https://docs.quadratic.to/reference/python-cell-reference/pandas-dataframe#referencing-a-range-of-cells) is missing from the `cells()` function. I believe this is supposed to be a direct alias of `getCells()`. Please correct me if I am wrong.
2. When passing the `first_row_header` argument, the row index of the dataframe returned starts from 1. I think that starting from 0 would be good for consistency and is what people expect.
This PR fixes these two issues.
`tests-python/test.py`
```
Launching unittests with arguments python -m unittest /quadratic/tests-python/test.py in /quadratic/tests-python …
```

Add missing argument to Getcells alias and fix dataframe indexing

---

.gitignore
src/core/gridGL/QuadraticGrid.tsx

This PR fixes a bug where the text will be blurry on devices that have a `devicePixelRatio` less than `1`. This is an edge-case I had to debug and fix on production for an enterprise Pixi application a few years ago, so when I was casually browsing the source code and noticed it, I forked it to add this fix so you don't get caught by it too. All this PR does is changes the check for your `resolution` Pixi configuration option to be a `<=` instead of a strict `===`. Effectively clamping the `resolution` to `2` if the `devicePixelRatio` is less than 1.0.
Having a `devicePixelRatio` less than 1.0 is generally pretty unusual, however it is much more common in enterprise environments (office workers, construction workers, product planners, etc) due to both accessibility tools or janky browser …

Fix: Blurry text when `devicePixelRatio` is less than one

---

src/core/computations/python/run_python.py

Enables following syntax:
```
1. grid[row                        , col                        ]
2. grid[row_slice_min:row_slice_max, col                        ]
3. grid[row                        , col_slice_min:col_slice_max]
4. grid[row_slice_min:row_slice_max, col_slice_min:col_slice_max]
```
TODO: Enable `first_row_header` parameter.
Options:
1. Pass parameter in dict. E.g. `grid[1:10, 1:10, {'first_row_header': True}]` ([ref](https://stackoverflow.com/questions/31916617/using-keyword-arguments-in-getitem-method-in-python))
2. Create two grid objects with and without built in `first_row_header` parameter. E.g. `grid` and `gridh`.

Add numpy-like indexing

---

src/ui/menus/TopBar/SubMenus/FormatMenu.tsx
src/ui/menus/TopBar/SubMenus/NumberFormatMenu.tsx
src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
src/ui/menus/TopBar/SubMenus/menuStyles.ts
src/ui/menus/TopBar/TopBar.tsx
src/ui/menus/TopBar/ZoomDropdown.tsx

This aims to refine and polish these aspects of the app:
1. Apply consistent UI copy and casing
2. Remove (redundant) menu label dividers
3. Remove (inconsistent application of) icons from menus
4. Tweak language for the sake of clarity
More detailed rationale for each change and a before/after snapshot of the changes:
There is some inconsistent casing in the UI copy. In some places you’ll find “Title Case”, in others “Sentence case”. It’s a seemingly minor detail, but helps provide solid polish and a sense of care to the overall app.
I suggested apply a standard approach to casing across the UI. Personally, I recommended going with “Sentence case” for many reasons, one being that it’s the most predictable for people writing copy and friendly for people reading copy ([this is a great …

fix: apply consistent UI copy casing, tweak menu design elements

---

src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/useGetBorderMenu.tsx
src/ui/menus/TopBar/SubMenus/menuStyles.ts

Fixes a number of issues described in [the corresponding Notion page](https://www.notion.so/Formatting-UI-Feedback-204dcd15ddce4db0a185409f02f1678c), including:
- Normalize menu item casing, e.g. "Fill Color" -> "Fill color"
- Remove unnecessary labels
- Style disabled menu icons so they also appear disabled
- Add icon to "Clear formatting" with a divider (to separate it from any one specific menu section)
- Add tooltips to border application buttons (and remove "selected" state of border buttons, as those are buttons to _apply_ a style, not representative of the current state of borders)
| Change | Before | After |
| --- | --- | --- |
| Formatting menu | <img width="199" alt="CleanShot 2023-01-11 at 12 04 31@2x" src="https://user-images.githubusercontent.com/1316441/211895396-65ccd3d6-8f9 …

fix: small UI tweaks

---

src/core/gridGL/interaction/keyboard/keyboardViewport.ts
src/core/gridGL/interaction/keyboard/useKeyboard.ts
src/ui/menus/KeyboardShortcut.tsx
src/ui/menus/TopBar/ZoomDropdown.tsx

Add support for shortcuts related to zoom controls and display them in the zoom menu bar.
Resolves a few takeaways from [the UI/UX research on navigating infinite canvas tools](https://www.notion.so/Navigation-Infinite-Canvas-Tools-23789227181b419e9a72444308343ccf)

feat: add zoom shortcuts

---

src/core/gridDB/localFiles.ts

Add a debouncing mechanism around the local storage saving procedure to unblock the thread and eliminate hang time on large batches of saves

PW // [PERFORMANCE FIX]: Debounce Save File Procedure

---

src/ui/menus/KeyboardShortcut.tsx
src/ui/menus/RightClickMenu/ContextMenu.tsx

Display keyboard shortcuts in the context menu (like we do in the zoom dropdown):

feat: add keyboard shortcuts to context menu

---

src/ui/menus/CommandPalette/ListItems/Format.tsx
src/ui/menus/ContextMenu/FloatingContextMenu.tsx
src/ui/menus/KeyboardShortcut.tsx
src/ui/menus/TopBar/SubMenus/DataMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/formatMenuStyles.scss
src/ui/menus/TopBar/SubMenus/NumberFormatMenu.tsx
src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx

- Add clear all formatting to the command palette (with shortcut)
- Removes stateful nature of bold/italic menus (we can bring this back one day, see #220)
- Removes (currently disabled) text alignment and text wrapping from formatting menu
- Fixes menu alignment/padding
- Fix so there's parity in ordering and grouping between format toolbar menu and format context menu
- Tries to resolve weirdness of top-level tooltips (tooltips could be interacted with, so it would show up even when your cursor went to the menu)
- Tried to fix this the best I could with the fact that we're trying to make two different UI libraries (`mui` and `react-menu`) work together. It could be better, but I don't think it's worth spending the time on right now.

fix: menus

---

src/ui/components/qColorPicker.tsx
src/ui/menus/ContextMenu/FloatingContextMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/formatMenuStyles.scss
src/ui/menus/TopBar/SubMenus/FormatMenu/useGetBorderMenu.tsx

feat: color picker style enhancements

---

src/ui/menus/ContextMenu/FloatingContextMenu.tsx

- Re-style the dividers in the formatting menu to contrast with the vertical column lines (so they don't blend in with each other) by 1) not letting them run to the edges of the widget, and 2) run lines perpendicular to column line
- Fix the 'text color' dropdown to not have box shadows (must've lost this change in a merge somewhere?)

fix: update floating formatting bar

---

src/core/computations/python/run_python.py

This follows on from https://github.com/quadratichq/quadratic/pull/128. 
To simplify the API it merges the `grid` cell accessor into a common `cells` accessor.
It can be used as follows:
```
1. cells[row                        , col                        ]
2. cells[row_slice_min:row_slice_max, col                        ]
3. cells[row                        , col_slice_min:col_slice_max]
4. cells[row_slice_min:row_slice_max, col_slice_min:col_slice_max]
```
In addition, the previous API below still works:
```
5. cells((col_min, row_min), (col_max, row_max))
6. cells((col_min, row_min), (col_max, row_max), first_row_header=True)
7. cell(col, row)
```
The following points still need consideration.
- Should we add `cell[row, col]`
- Should the row/col indices be swapped in `cell()` and …

[WIP] Merge grid with cells

---

src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx

Re-organize the file menu and make it more standard in terms of organization and hierarchy (and match names/labels to what's in the command palette):

feat: file menu reorganization

---

src/core/gridGL/interaction/keyboard/useKeyboard.ts
src/ui/menus/CommandPalette/ListItems/Format.tsx
src/ui/menus/ContextMenu/FloatingContextMenu.tsx
src/ui/menus/TopBar/SubMenus/FormatMenu/FormatMenu.tsx
src/ui/menus/TopBar/SubMenus/useBorders.ts
src/ui/menus/TopBar/SubMenus/useClearAllFormatting.ts
src/ui/menus/TopBar/SubMenus/useFormatCells.ts

Bug:
1. Add some borders and formatting
2. Clear formatting
3. Press Undo
Previously it would be two Undos to get back, one for borders one for formatting. now it is one.

fix double undo bug for clearing all formatting

---

src/ui/menus/TopBar/TopBar.tsx

- Change the "Command palette" icon from a pure search icon to an list/search icon (feels like this more closely matches the essence of the command bar’s functionality, e.g. 'search a list of actions')
- Change the 'show cell type outline' toggle to use primary color (we don't use the secondary color anywhere that i'm aware of, feels more cohesive with the rest of the app's accent color to use primary IMO)
- Change name from "Command palette" to "Quick actions"
---
Rationale:
Figma calls their feature ["Quick actions"](https://help.figma.com/hc/en-us/articles/360040328653-Use-shortcuts-and-quick-actions)
VSCode calls it the "Command palette"
Google Sheets calls their (equivalent) "Search the menus"
Personally I like "Quick actions" as it feels less developer-y. If you're not familiar with …

refactor: tweak top bar icon and style

---

src/gridGL/UI/GridLines.ts

Fixes #285. I'm still not sure who sets gridLines.visible = true, but this patch ensures that even if they are visible, the grid line drawing is cleared.

ensures grid lines are cleared

---

.github/workflows/test-unit.yml
src/grid/sheet/Sheet.ts
src/grid/sheet/tests/gridRenderDependency.test.ts
src/gridGL/UI/cells/Cells.ts
src/gridGL/UI/cells/CellsArray.ts

add a separate dependency list for array lines

---

src/ui/menus/TopBar/TopBar.tsx

Tidy Header on Mobile

---

src/gridGL/pixiApp/PixiApp.ts
src/ui/QuadraticUI.tsx
src/ui/components/PresentationModeHint.tsx

Make the presentation mode go full screen by hiding header/footer and provide a little UI hint on how to get out of that mode that disappears after ~3 seconds
The code editor would stay open if it's already open
---
Figma does this nicely when you're in a prototype and you show/hide the figma UI, it tells you how to exit and hides the message after `n ` seconds

feat: make presentation mode go full screen

---

src/gridGL/pixiApp/PixiApp.ts

I broke grid resizing [here](https://github.com/quadratichq/quadratic/pull/326/commits/44b1dccf2bd1944e35b974c71aa9666f58557389#diff-07dfae82d5a245c6f7a92c5b147bca8506b4cc9938ffcd2c5e634ae8c73cd4aeL172) so right now when you resize the browser, the grid doesn't redraw (it stretches like a bitmap image).
But this fixes it by making sure `this` is bound to the pixi app (not the window)

fix: bind `this` to the correct context

---

quadratic-core/Cargo.lock
quadratic-core/Cargo.toml
quadratic-core/src/formulas/ast.rs
quadratic-core/src/formulas/errors.rs
quadratic-core/src/formulas/lexer.rs
quadratic-core/src/formulas/parser/rules/expression.rs
quadratic-core/src/formulas/tests.rs
quadratic-core/src/formulas/value.rs
src/constants/urls.ts

Uses same syntax as Excel: e.g., `{1, 2, 3; 4, 5, 6}`
Empty arrays and nonrectangular arrays are not allowed
Also added link to new [formula docs](https://docs.quadratichq.com/formulas)

Add array literals in formulas

---

src/constants/urls.ts
src/ui/menus/CodeEditor/Console.tsx

Per [David's feedback in Slack](https://quadratichq.slack.com/archives/C03KXQTH5TP/p1678474296090159) update it so we only link to the Quadratic docs (which can then link to the individual libraries). Also fix the docs link.
Also: added an extra part in our current docs about these packages.

fix: links to docs

---

src/gridGL/quadrants/Quadrant.ts

Fixes #331 
A more robust fix for this bug is found in #308, where it properly rebuilds the quadrants on a file load. This PR will fix the current bug to avoid the black bars.

Fix an issue with subquadrant using texture size <= 0

---

src/index.js
src/ui/menus/CodeEditor/CodeEditor.tsx

Remove the layout shift when you hit the "Save & run" button by just disabling the icon and putting the async loading indicator next to it (with a little extra padding)
Before:
After:
Subtle — but small things add up!

fix: tweak async run indicator on code editor

---

src/storage/GridFile.test.ts
src/storage/GridFile.ts
src/storage/useLocalFiles.ts

The old file schema used integers as enums for border types whereas the new schema [introduced here](https://github.com/quadratichq/quadratic/pull/308/files#diff-fb2ecd77a7c43aa1f68a862e8866d079391f51b6ae9665059d523221fdf5256fL44-L51) uses human readable strings.
This results in old files with special borders having integers as values (instead of strings) and therefore not passing zod parsing
For example, the new file formats look like this:
```json
"borders": [
{
"x": 5,
"y": 6,
"vertical": {
"type": "dashed"
}
}
]
```
Whereas the previous file format was:
```json
"borders": [
{
"x": 5,
"y": 6,
"vertical": {
"type": 4
}
}
]
```

fix: border type enums as strings

---

src/ui/QuadraticUI.tsx
src/ui/components/ReadOnlyDialog.tsx

For people who show up to the site on a mobile device, show a dialog indicating that the app is best on desktop.
To test:
- Should not fire for a desktop device
- Should only show the first time you come to the app (on mobile) and, once dismissed, you should never see this message again (unless you clear your cache, as it's stored in localStorage)

feat: add read-only dialog for mobile

---

src/theme/colors.ts

Use classic green/red connotations for add/remove (& pull colors from material UI):

refactor: colors on add/remove

---

src/gridGL/interaction/pointer/PointerAutoComplete/PointerAutoComplete.ts

Today when you drag the cursor on a horizontal selection _other than the very last row_, the UI communicates a "delete" action will happen on your initial selection (which isn't true).
This PR fixes that so the "delete" UI indication only happens when you shrink your initial selection irregardless of row.

fix: only indicate "delete" on horizontal drag when you shrink the initial selection

---

package-lock.json

Running `npm run build` results in this output:
```
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
So I ran the command to do the update.

chore: update browserslist

---

src/debugFlags.ts
src/quadratic/QuadraticApp.tsx
src/ui/menus/TopBar/SubMenus/useGridSettings.ts

**Problem**
Currently, if you open then close the editor and go into presentation mode, the header/footer don't disappear. Similarly, if you open the code editor and trigger presentation mode, it doesn't hide everything. Only once you go into presentation mode _again_ does it then work.
**Solution**
This problem was caused because `useGridSettings` was a hook being called across multiple components. Each use of `useGridSettings` was its own instance of the hook with it's own state and setState functions. This caused state across components to fall out of sync (even though it was all sourced from the same place: localStorage).
The solution, in this case, was to lift that state into recoil and have `useGridSettings` return _the recoil state_ as well as discrete functions for manipulation …

fix: grid settings

---

README.md
src/ui/components/ConditionalWrapper.tsx
src/ui/components/TooltipHint.tsx
src/ui/menus/CodeEditor/AICodeBlockParser.tsx
src/ui/menus/CodeEditor/AITab.css
src/ui/menus/CodeEditor/AITab.tsx

This PR includes two UI/UX improvements:
1. If the user scrolls to the bottom of the AI Assistant panel, the latest response will stay pinned to the bottom as the response streams in
2. The user is provided a "Stop" button that will cancel the streaming AI chat.

feat: AI ui/ux enhancements

---

src/hooks/useGenerateLocalFiles.tsx

If somebody links to a file with spaces in the url, e.g. `?file=file%20name.grid` make sure the file name shows as "file name" in the app once imported (not "file%20name")

fix: support spaces when importing file from url

---

src/hooks/useGenerateLocalFiles.tsx
src/ui/QuadraticUI.tsx
src/ui/menus/CodeEditor/CodeEditor.tsx
src/ui/menus/CommandPalette/ListItems/File.tsx
src/ui/menus/FileMenu/FileMenu.tsx
src/ui/menus/FileMenu/FileMenuTabs.tsx
src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
src/ui/menus/TopBar/TopBar.tsx

Fixes #462 
Note: there are currently 3 different places that can create a new file:
1. Quadratic menu (File -> New)
2. Command palette
3. File menu (File -> Open -> Create file)
No. 2 & 3 suffer from this bug where if the code editor is open when you create a new file it doesn't disappear when the new file is opened.

fix: close editor when creating new file

---

quadratic-core/Cargo.lock
quadratic-core/Cargo.toml
quadratic-core/src/lib.rs

Unfortunately this won't apply to formulas evaluated while the bug was in prod, but after rerunning each formula it should be fixed

Fix formulas not automatically updating

---

src/constants/app.ts

Example file is already in the repo, so it's just a matter of registering it with the UI as an example.

feat: add Open AI example file

---

src/schemas/GridFileV1_2.ts

Fixes #415 
I opted to just change the existing version `1.2` file schema, rather than create a new one, since this change is additive and merely accepts more kinds of data in `array_output` than what was being allowed previously. 
Previously: `array_output` was an optional 1 or 2d array of string, number, boolean, or null.
Now: `array_output` is an optional 1 or 2d array of anything.
- Open a new file, name it "This shouldn't be busted"
- For a python cell, return the value `[[[1,2,3]]]`
- <img width="523" alt="CleanShot 2023-06-13 at 13 50 58@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/683367ce-9858-4d82-9722-5181bcaf001b">
- For another python cell, return the value `[{1}, {2}]`
- <img width="518" alt="CleanShot 2023-06-13 at 13 51 25@2x" …

fix: allow anything in `array_output`

---

quadratic-core/Cargo.lock
quadratic-core/Cargo.toml
quadratic-core/src/formulas/functions/trigonometry.rs

In Excel, `ATAN(0, 0)` returns zero. This changes Quadratic's behavior to match Excel

Fix `ATAN2(0, 0)` semantics

---

quadratic-core/Cargo.lock
quadratic-core/Cargo.toml
quadratic-core/src/formulas/ast.rs
quadratic-core/src/formulas/functions/logic.rs
quadratic-core/src/formulas/functions/macros.rs
quadratic-core/src/formulas/functions/mod.rs
quadratic-core/src/formulas/lexer.rs
quadratic-core/src/formulas/parser/rules/atoms.rs
quadratic-core/src/formulas/parser/rules/expression.rs
quadratic-core/src/formulas/tests.rs

This PR makes `TRUE` and `FALSE` work directly in formulas. So `IF(TRUE(), 1, 2)` is equivalent to `IF(TRUE, 1, 2)`. This is consistent with Excel.

Add boolean parsing in formulas

---

quadratic-api/package-lock.json
quadratic-api/package.json
quadratic-api/tsconfig.json

Previously, our typescript config was set to node 16, but our node engine was set to 18 (a mismatch).
This PR upgrades to node 20 (which [goes LTS in October](https://github.com/nodejs/release#release-schedule)), typescript 5, and a matching tsconfig that extends `@tsconfig/node20`.
To test (locally):
- Upgrade local version of node to v20.x
- `cd quadratic-api` and  `npm i` and `npm start`
- Ensure the app runs
To test (staging):
- Promote this branch in staging, and see that node 20 is installed and runs
**Merge note:** [Heroku says](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) they key off the `engine` in `package.json` so, once merged, I'm assuming heroku will automatically update to node20.

chore: upgrade API to node 20 and typescript 5

---

src/schemas/GridFileV1.ts
src/schemas/GridFileV1_1.ts
src/schemas/validateGridFile.test.ts
src/schemas/validateGridFile.ts

v1.2 version of the file schema allowed `any` for `array_output` to fix a bug (#561)
but if older versions of files have those same errors but are otherwise valid, they'll fail to load.
this makes it so (retroactively) we make previous file versions support `any` for `array_output` (as the code would, sometimes, support writing files out in an "invalid" way with more than just string|number|boolean in `array_output`)
**To test:**
- Try to import a v1.1 version of a file where the `array_output` is a value that's supported in v1.2 ([test-file.grid.txt](https://github.com/quadratichq/quadratic/files/11885332/test-file.grid.txt))
- Ensure that the file imports correctly

fix: allow any for array_output in older versions of the schema

---

src/gridGL/UI/gridHeadings/GridHeadings.ts
src/theme/colors.ts

I never loved that the accent color (blue) is being used for the grid heading lines.
This changes it from being the accent color (used to indicate "active"-ness in the grid, e.g. cursor color, active cell heading background color, etc.) to our neutral "gray" which is used for the other heading lines.

refactor: tweak color of heading grid lines

---

package-lock.json
package.json
src/ui/components/CodeSnippet.tsx
src/ui/menus/CodeEditor/AICodeBlockParser.test.ts
src/ui/menus/CodeEditor/AICodeBlockParser.tsx
src/ui/menus/CodeEditor/AITab.tsx
src/ui/menus/CodeEditor/CodeEditor.tsx
src/ui/menus/CodeEditor/Console.tsx

A few enhancements to the interface for interacting with the AI assistant.
Format code blocks, even before we get to the terminal backticks ```
Fixes #473
Before:
After:
Fixes #539 Copy contents of a block of code.
Cleaned up some spacing and alignment issues and [changed some config options of the editor](https://github.com/quadratichq/quadratic/pull/583/files#r1245905588) as well as tweaking the AI tab zero state.

feat: enhance AI assistant ui/x

---

src/quadratic/AnalyticsProvider.tsx

feat: mixpanel proxy

---

.vscode/settings.json

Reference: https://dev.to/shanesc/how-to-sort-and-cleanup-imports-on-save-in-vs-code-52p1
Example before:
After:

chore: add setting so VSCode automatically sorts imports

---

src/hooks/useAlertOnUnsavedChanges.ts
src/ui/menus/CodeEditor/CodeEditor.tsx

fixes bug #611

---

src/auth.ts
src/router.tsx

Was seeing this issue when you come back to the app after a day or so:
The app renders because `isAuthenticated` comes back as true.
_But_, the `.getToken()` fails because, I believe, it has expired. Because of this, the app renders but the part of the UI that relies on an API call fails because the auth client fails to get the token.
The best way to simulate this is to login and change the expires time to something in the past (e.g. `0`). Then reload the app and you'll see the same error screen above.
This fixes this problem by redirecting the user to login if the `getToken` call fails

fix: redirect to login when getting token silently fails

---

src/gridGL/UI/Cursor.ts

Today people without edit access to a shared file can use the autocomplete  to edit the document.
What we want is to disallow that and hide the little square box if you can't edit a doc.

fix: hide autocomplete cursor indicator if user doesn't have permission to edit

---

src/auth.ts
src/constants/routes.ts
src/router.tsx
src/ui/components/PermissionOverlay.tsx

For users viewing a shared file who are not authenticated, we show a message saying they need to login.
If they hit "Log in" they get taken to the auth0 login page:
Where they can login, or if they are new, sign up.
This PR adds an additional "Sign up" button
Which allows them to jump directly to the sign up page:
Previous behavior:
- Load a shared file as a logged out user
- Click "log in"
- [app sends user to `/login` which then redirects them to auth0]
- Hit the back button
- End up on auth0 again
When you hit the back button, it's navigating you to `/login` which automatically redirects you back to auth0. So you get stuck in this loop where hitting "back" doesn't take you back to the file.
New behavior:
- Load a shared file as a logged out user
- Click "log in"
- [app sends user to …

feat: add signup button, fix 'back' button on login

---

src/grid/controller/Sheets.ts
src/ui/menus/ContextMenu/FloatingContextMenu.tsx
src/ui/menus/SheetBar/SheetBarTab.tsx

fix FloatingContextMenu when switching tabs

---

src/constants/appConstants.ts
src/grid/actions/clipboard/clipboard.ts
src/gridGL/interaction/keyboard/keyboardClipboard.ts
src/ui/menus/CommandPalette/ListItems/Edit.tsx
src/ui/menus/ContextMenu/FloatingContextMenu.tsx

"Copy as PNG" was working from the floating context menu but not from the command palette.
When you choose "Copy as PNG" from the command palette, the little toast notification would pop up saying it was copied
But if you went to paste that PNG somewhere (e.g. Slack) that image was not in your clipboard.
It looks like the command palette version of "copy as PNG" was pointing to some old code, whereas the floating context menu (and SHIFT + CMD + C) were using the right functions. So I had it use the same function.
I also noticed that they all were doing the same thing (e.g. copy to clipboard, then fire a toast notification) so I moved all of that functionality into the main function body. Now it's one function call from all three places.
I also added checks in case the "copy as PNG" fails, …

fix: copy PNG to clipboard from command palette

---

src/ui/menus/CommandPalette/ListItems/Sheets.tsx

Updates the command palette to:
1. Exclude the _current sheet_ from the list of sheets you can switch to
2. For sheets that have a color highlight, show it in the command palette as well
[Slack convo](https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1695415884523609)

feat: improved sheet switcher in command palette

---

src/ui/menus/SheetBar/SheetBar.tsx
src/ui/menus/SheetBar/SheetBarTabContextMenu.tsx

I suppose we could add analytics for tons of stuff related to sheets (e.g. was it renamed? was its order moved? was a color assigned? etc.)
But I went with just adding basic event tracking around whether people are using it at all, e.g. events for:
- Add a sheet
- Duplicate a sheet
- Delete a sheet

feat: add sheets analytics

---

src/dashboard/FileRoute.tsx
src/schemas/compareVersions.test.ts
src/schemas/compareVersions.ts

The old version comparison would fail (in the future) for a version comparison like:
"1.10" > "1.8"
This is fixed in this PR with the `compareVersions` function (which includes tests).

fix: proper version comparison

---

quadratic-core/src/grid/sheet.rs
quadratic-core/src/wasm_bindings/controller/cells.rs

Next get cell value

---

quadratic-core/src/controller/formula.rs
quadratic-core/src/formulas/cell_ref.rs
quadratic-core/src/formulas/parser/rules/atoms.rs
quadratic-core/src/formulas/parser/rules/expression.rs
quadratic-core/src/formulas/tests.rs
quadratic-core/src/span.rs
src/gridGL/pixiApp/highlightedCells.ts

The params & return value stay the same. `parse_formula()` just does parsing, no semantics, so it only knows sheet names given by the user, not sheet IDs or the current sheet. E.g., `SUM(A1:A10)` would have `sheet: null` for the cell reference `A1:A10` but `SUM(MySheet!A1:A10)` would have `sheet: "MySheet"` for the cell reference `MySheet!A1:A10`.
To review:
- Look over the new tests and see if anything's missing.

Add sheet info to `parse_formula()`

---

src/constants/urls.ts
src/ui/components/TooltipHint.tsx
src/ui/menus/CodeEditor/CodeEditorHeader.tsx
src/ui/menus/CodeEditor/Console.tsx

closes #798
- updated docs URLS
- Remove documentation tab from CodeEditor
- Add docs link in CodeEditorHeader

Update Docs Links

---

src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx

Fixes #815
When loading documents on mobile, they previously show up blank until moving the viewport.

Fix blank grid loading on mobile

---

src/actions.ts
src/ui/menus/CommandPalette/ListItems/File.tsx

Fixes bug where files were not duplicating from within the app
Also fixes bug where duplicating from within the command palette wasn't working.
Try duplicating a file from all the places where you can do it:
- Command palette -> Duplicate file
- Quadratic menu -> File -> Duplicate
- File name dropdown -> Duplicate
- Shared file overlay -> Duplicate

fix: duplicate file

---

src/ui/menus/CodeEditor/Console.tsx

Was using the app myself — toggling between writing code and looking at the output and asking the AI for help — what would make the indicator next to the "Console" tab even more helpful would be to indicate whether what's being shown in the console is standard output or an error.
This feature turns the indicator red if it's an error.
As an example, I'm writing code and something is wrong. So i go to the AI and ask for help. It tells me how to fix it, I change the code and re-run the example. I can't tell whether it fixed it unless I go back to the "Console" tag and see if there's an error.
With this fix, I can know without switching away from the AI tab, which makes collaborating with the AI assistant much more helpful as you can write code and know when you create or fix errors. …

feat: indicate error state in console badge indicator

---

src/ui/menus/BottomBar/SelectionSummary.tsx

The current implementation of the bottom bar outputs a number that is _really_ big.
Excel caps this number at 9 digits beyond the decimal
So we do the same thing:
Also: excel provides the ability for you to click and copy the values in the bottom bar. This allows you to do the same thing in Quadratic.

feat: improve bottom bar stats functionality

---

.github/workflows/lint.yml
CONTRIBUTING.md
package.json
quadratic-client/package.json

note: this removes `npm run watch:wasm:types` from `npm start` to avoid double rust compiles on rust changes. `npm run build:wasm:types` is run only once when the script starts. To rebuild the rust types, you need to manually call `npm run build:wasm:types`, or restart `npm start`

Improvements to npm scripts

---

quadratic-client/src/grid/controller/Grid.ts
quadratic-client/src/grid/controller/Sheets.ts
quadratic-client/src/gridGL/cells/CellsSheets.ts
quadratic-client/src/gridGL/htmlCells/HtmlCell.ts
quadratic-client/src/gridGL/htmlCells/htmlCellsHandler.ts
quadratic-client/src/gridGL/interaction/pointer/PointerHeading.ts
scripts/run-ci-build.sh
vercel.json

fixed sheet mutli-sheet rendering bug

---

quadratic-client/src/constants/urls.ts

looks like we changed the support URL to /contact

/support URL changed to /contact

---

quadratic-client/src/dashboard/FileRoute.tsx
quadratic-client/src/ui/menus/TopBar/TopBar.tsx

Make the embed experience be like the user is anonymous, regardless of whether they are logged in or not.
Before (user avatar is visible, file operations are visible):
After (user avatars are gone, file operations are hidden):
You won't be able to see this on deploy previews since they are on the vercel domain. You'd have to pull this down and test locally — or just merge and see that it works hehe

feat: make embeds read-only

---

.github/workflows/ci.yml
Cargo.lock
quadratic-client/src/multiplayer/multiplayer.ts
quadratic-client/src/multiplayer/multiplayerTypes.ts
quadratic-multiplayer/Cargo.toml
quadratic-multiplayer/package.json
quadratic-multiplayer/src/auth.rs
quadratic-multiplayer/src/background_worker.rs
quadratic-multiplayer/src/file.rs
quadratic-multiplayer/src/main.rs
quadratic-multiplayer/src/message/handle.rs
quadratic-multiplayer/src/message/mod.rs
quadratic-multiplayer/src/message/request.rs
quadratic-multiplayer/src/message/response.rs
quadratic-multiplayer/src/server.rs
quadratic-multiplayer/src/state/connection.rs
quadratic-multiplayer/src/state/mod.rs
quadratic-multiplayer/src/state/room.rs
quadratic-multiplayer/src/state/transaction_queue.rs
quadratic-multiplayer/src/state/user.rs
quadratic-multiplayer/src/test_util.rs

Mp transaction queue

---

quadratic-client/src/utils/analytics.ts

Per a request from David:
> Hey we want to push GTag email so google Ads knows when someone is new. We just need this code snippet...And we have to fill out the email with Auth0 data
```
dataLayer.push({
'event': 'Pageview',
'userData': {
'email': '{{ email }}'
}
}); 
```

feat: update gtag analytics

---

quadratic-client/src/atoms/editorInteractionStateAtom.ts
quadratic-client/src/gridGL/interaction/CellInput.tsx
quadratic-client/src/gridGL/interaction/keyboard/keyboardCell.ts
quadratic-client/src/gridGL/interaction/keyboard/keyboardViewport.ts
quadratic-client/src/gridGL/interaction/pointer/doubleClickCell.ts
quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
quadratic-client/src/ui/menus/CodeEditor/CodeEditorBody.tsx

The testing matrix is rather large:
__Possible states__
1. Code Editor is open or closed
2. Code Editor has changes or not
3. Code Editor has focus or not
__Triggers__
__Save Dialog choice__
Need to check all the triggers against the three results of the dialog: Save and Run, Discard, and Cancel. 
* Save and Run should save and run the cell and update it before performing the trigger
* Cancel should revert the original code cell's contents before performing the trigger
* Cancel should always leave the code cell the way it was with the unsaved change and cancel the triggering event

Improve CodeEditor warning dialog

---

quadratic-api/src/auth0/profile.ts
quadratic-api/src/middleware/user.test.ts
quadratic-api/src/middleware/user.ts
quadratic-api/src/routes/v0/files.$uuid.invites.POST.ts
quadratic-api/src/routes/v0/teams.$uuid.GET.ts
quadratic-api/src/routes/v0/teams.$uuid.invites.POST.ts
quadratic-api/src/tests/testDataGenerator.ts

When a new user comes in to the system:
- Create them in the User table of the database
- Find any outstanding invites that they have to a team or a file
- Make them members of the team or file
- Delete the old invites
Tested this locally by:
- Deleting my quadratichq.com user from my local database and then from auth0 (staging)
- Use my personal gmail.com to invite my quadartichq.com user to 1 file and 1 team
- Log in to the app using my quadrtichq.com user and see that immediately belong to 1 team and have 1 file in the "Share with me" tab
- Look in my local database and see that the old invites were removed and associations made to the team/file

feat: new user association

---

quadratic-client/src/api/apiClient.ts
quadratic-client/src/components/ShareDialog.tsx
quadratic-client/src/dashboard/components/FilesListItem.tsx
quadratic-client/src/ui/menus/TopBar/TopBarShareButton.tsx

Mixpanel events related to file sharing (based on [Slack conversation](https://quadratichq.slack.com/archives/C03VC0Q1MPA/p1704999356266969)).
```sh
[FileSharing].menu.open, { context: 'app' | 'dashboard', pathname?: string }
[FileSharing].invite.create
[FileSharing].invite.delete
[FileSharing].user.updateRole
[FileSharing].user.remove
[FileSharing].publicLinkAccess.update, { value: 'NOT_SHARED' | 'EDIT' | 'READONLY' }
[FileSharing].publicLinkAccess.clickCopyLink
```
Notes:
- When updating a role or removing a user, I don't differentiate between this being the user updating/removing themselves or doing it to another user. We _could_ do that, but it'll involve a bit more code. If we care about that differentiation in the analytics, I can do it. Otherwise it's not worth the effort.
- I …

feat: mixpanel events

---

quadratic-api/src/middleware/validateRequestSchema.ts
quadratic-api/src/routes/v0/files.$uuid.invites.POST.test.ts
quadratic-api/src/routes/v0/files.$uuid.invites.POST.ts
quadratic-client/src/components/ShareDialog.tsx
quadratic-shared/typesAndSchemas.ts

When somebody invites someone else by email, e.g. `Jim.nielsen@quadratichq.com`, we lookup that email via auth0 and it does a case-insensitive search for the email. 
That means if I already have an account in auth0 with the email `jim.nielsen@quadratichq.com`, a match will be sent back from Auth0 and we will associate that user with the file on our side (email case sensitivity doesn't matter here, as we don't store the email).
However, if no match is found, that email will be stored as an invite in our database _just the way it was typed_. Then an email will be sent to `Jim.nielsen@qudartichq.com` and, because (most) emails are case-insensitive, it will be received.
If that person then comes to Quadratic and creates an account (whether through manual credentials or Google), Auth0 is going …

fix: email case sensitivity when inviting someone to a file

---

quadratic-api/src/routes/v0/files.$uuid.thumbnail.POST.ts
quadratic-api/src/routes/v0/files.GET.ts

Files used to be ordered by last modified by default.
This adds `updatedDate: new Date(),` to the thumbnail endpoint.

bug: Fix File updatedDate

---

quadratic-api/src/auth0/profile.ts

A sentry error got triggered but we can't see any information in Sentry about who triggered it.
I believe this is because the entire `auth0User` was undefined and so it got serialized as JSON to `{}`
So now we explicitly pass in the auth0Id that it was trying to get, so we'll know who triggered this. e.g. in the future this would log something like:
```
extra: {
auth0IdInOurDb: "google-oauth2|000...",
// `auth0UserResult` would be `undefined`,
}
```

fix: log extra data to sentry when no auth0 profile is found

---

quadratic-client/src/grid/actions/clipboard/clipboard.ts

To repro in main:
1. open quadratic in safari
2. add text content to your clipboard
3. double click to edit a cell
4. click somewhere else
5. try to copy a cell or paste the clipboard content
Expected: copy and paste works
Safari: copy will beep to let you know it was not successful; paste will not work

Fix safari clipboard

---

quadratic-client/src/web-workers/pythonWebWorker/python.ts

In main, if you try to get a value from a different sheet, it throws an error. This fixes this so the code's console properly shows the error instead of throwing an exception.
To replicate run this:
```
cell(1, 2, "no sheet")
```
in Python in both main and this branch.

Fixes a bug with Sheet Not Found in Python

---

quadratic-client/src/constants/routes.ts
quadratic-client/src/dashboard/components/FilesListItem.tsx
quadratic-client/src/router.tsx
quadratic-client/src/routes/_dashboard.tsx

Adds an option to move a file in the file context menu.
It will only ever show, at max, 2 teams in the menu.
If you're on a team, it will show the option to move to "my files" as well as (up to 2) other teams
If you're in your personal files, it will show (up to 2) teams
You have to have edit access to the team to be able to see the option to move it.

feat: move files

---

quadratic-client/src/ui/menus/CodeEditor/AITab.tsx
quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
quadratic-client/src/ui/menus/CodeEditor/Console.tsx

AI doesn't work in prod on any cell with a chart output. This is because the ~ 3mb that each chart takes up (wow!) is sent as context to the AI API.
I changed it to simply send the std error, this fixes the issue.

fix AI tab when output has a chart

---

quadratic-kernels/python-wasm/package.sh
quadratic-kernels/python-wasm/setup-poetry.sh

The flag only verifies that the file in the path exists; without it, the command verifies all directories exist, but it ignores the last file. In this scenario, since we're getting the file from `BASH_SOURCE`, the behavior should still be sufficient.

Remove `realpath` flag that doesn't support OSX

---

quadratic-api/src/middleware/getFile.ts
quadratic-api/src/utils/permissions.ts

To reproduce:
- Create a file
- Turn on the public link to "Edit"
- Open the shared link in incognito mode
See that the user, who is not logged in, is receiving a `FILE_EDIT` permission.
This fixes the issue so a user who is not logged in will never get a `FILE_EDIT` permission.

fix: incognito mode gets edit access

---

quadratic-api/src/aws/s3.ts

If you load the dashboard and scroll down to all your files after 2 minutes, the images won't load. This is because the browser lazy loads them and the URLs are only valid for 2 minutes. 
This ups that to 7 days.

bug: Thumbnails on Dashboard

---

quadratic-core/src/controller/dependencies.rs
quadratic-core/src/controller/execution/execute_operation/execute_values.rs

Fixes #1185.
SetCellValues dependency checks would add (+1, +1) to its rect when checking whether it triggered a code cell run.

Fix SetCellValues dependencies check

---

quadratic-kernels/python-wasm/quadratic_py/process_output.py
quadratic-kernels/python-wasm/quadratic_py/run_python.py
quadratic-kernels/python-wasm/tests/process_output_test.py
quadratic-kernels/python-wasm/tests/test.py

Moves processing output into it's own function to make it possible to test

🚢 Refactor run_python to make it more testable

---

quadratic-client/src/web-workers/pythonWebWorker/python.worker.ts
quadratic-kernels/python-wasm/quadratic_py/run_python.py

Moves global definition to `run_python` so it is called on every run instead of only on first load.

Fix bug when redefining `c` in Python

---

quadratic-client/vite.config.js

I was having problems runnig main in dev. I changed vite.config.js so plugins only includes the `sentryVitePlugin` when the SENTRY_AUTH_TOKEN is defined.

Update vite config to turn off sentryVitePlugin when env not defined

---

quadratic-client/src/ui/menus/CodeEditor/ResizeControl.css

Today (in Safari) when you resize the code editor, the browser tries to do text selection making the experience really strange as you drag.
https://github.com/quadratichq/quadratic/assets/1316441/e77281c5-7503-431c-a33e-e975f688a2c3
This fixes that.

fix: text selection on code editor resize (safari)

---

quadratic-client/src/app/gridGL/pixiApp/pixiApp.css
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
quadratic-client/src/app/ui/menus/CodeEditor/SnippetsPopover.tsx

Because the code editor stays open, even when you switch between code cells, we need to show the sheet name when the code editor is open for a cell that's not in the currently active sheet.
This PR does that. It also refines aspects of the code editor header, including:
- Fixes problem where code editor header height was different across different cells
- Moves the unsaved indicator over the file to account for sheet names being variable in length
- Cell type head is hoverable and displays the cell type as well as a note that changes are unsaved (where relevant)
- Fixes problem where double clicking in canvas highlights tab text
https://github.com/quadratichq/quadratic/assets/1316441/797a0396-4234-40b6-b8a6-e1facfea25a5

fix: show sheet name in code editor header

---

quadratic-client/src/app/ui/components/FileUploadWrapper.tsx
quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts

Importing a bad .parquet or .csv file will trigger a snackbar error:

Show import errors to users

---

quadratic-client/src/routes/files.tsx

Fixes the small 2px offset for all non-highlighted items in the files list zero state (previously the non-highlited items were inset)

fix: border offset

---

quadratic-core/src/controller/operations/borders.rs
quadratic-core/src/controller/user_actions/borders.rs
quadratic-core/src/grid/borders/sheet.rs

closes #1231 
Changes:-
- Check if the new SheetBorder render for the rect is same as current SheetBorder render, then toggle the selected border.
- If new render is different, apply new border selection as before.
[toggle_borders.webm](https://github.com/quadratichq/quadratic/assets/54364088/7294d7f5-bf37-4d5e-957c-05fc9aef0a37)

feat: toggle borders

---

quadratic-kernels/python-wasm/quadratic_py/utils.py
quadratic-kernels/python-wasm/tests/test.py

closes #1113 
closes #1396 
closes #1395 
Bug:
`cells((0,0), (0,10)).sum()` is converted into `await cells((0,0), (0,10)).sum()`
Solution:
Wrap async function call in `(await <function-call>)` 
i.e. convert `cells((0,0), (0,10)).sum()` into `(await cells((0,0), (0,10))).sum()`
Changes:
- Updated regex to wrap async function calls in `(await <function-call>)`
- Updated regex to replace `c((x,y), ...)` & `cell((x,y), ...)` with `cells((x,y), ...)`

fix(python): wrap async functions in `(await <function-call>)`, replace `c((x,y), ...)` `cell((x,y), ...)` with `cells((x,y), ...)`

---

quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
quadratic-client/src/app/gridGL/interaction/viewportHelper.ts

closes #1053 
Changes:
- Added support for PgUp, PgDown, Home, End, Cmd+Home, Cmd+End with following behaviour:
- PgUp - Moves the sheet to exact one screen up.
- PgDown - Moves the sheet to exact one screen down.
- Home - Moves the cursor to the beginning of row, if the row has content. Nothing happens if the row is empty.
- Cmd+Home - Moves the cursor to (0, 0). Also resets the viewport with (0, 0) in top corner.
- End - Moves the cursor to the end of row, if the row has content. Nothing happens if the row is empty.
- Cmd+End - Moves the cursor to the last occupied cell in sheet.

feat: PgUp, PgDown, Home, End, Cmd+Home, Cmd+End support

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts

This fixes a bug where a line may wrap if it finds \n in a CodeCell (we already strip \n from text entered by the user).
The \n is stripped in the renderer for now.
We may want to revisit this once we actually support word wrapping (see https://github.com/quadratichq/quadratic/pull/1406)
Closes #1433

replace \n from code to ensure we don't wrap

---

README.md
quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts

Pressing up or down arrow when editing a normal cell properly moves you one cell.

Fix bug with leaving edit cell with up or down arrow

---

quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx

fix: kernel button in bottom bar doesn't behave like other buttons

---

quadratic-client/src/app/gridGL/HTMLGrid/CodeHint.tsx

Fixes bug with `press / to code` showing over content.
See https://quadratichq.slack.com/archives/C06Q34HGV8A/p1720119206871539

Code hint shouldn't show on when content in cell

---

quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts

Fixes #1484 
The correct behavior is if you double click on a CodeRun, you open the code cell that generated the CodeRun. We were not adjusting the cursor with one of the PR changes.

Fix bug with double clicking in cell within CodeRun

---

quadratic-client/src/app/gridGL/UI/Cursor.ts
quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts

Improve mouse interaction with move cells

---

infra/connection/connection.ts
infra/connection/connection_network.ts
infra/shared/securityGroups.ts

- Scaling connection service via autoscaling group
- All outbound connections are made via NAT with 2 static IPs
- Instances are closed to inbound traffic except via ELB with SSL termination
- Uses a new VPC that is not the same as the one with the other services in it (so our connection service can't try to connect to any private redis or postgres datastores)

Next connections infra prod 2

---

quadratic-api/src/utils/crypto.test.ts

Fixes a brittle test in CI, though I could not duplicate the false positive locally.

Append characters to the end of the text to avoid false positives

---

quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx

Fixes #1570
Command palette now properly closes when go to menu dialog is triggered

fix go to cell in command palette

---

quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
quadratic-core/src/controller/operations/formats.rs
quadratic-core/src/controller/user_actions/borders.rs
quadratic-core/src/grid/bounds.rs
quadratic-core/src/grid/sheet/bounds.rs

Fixes #1583 
Note: the clear borders implementation is limited to selections containing rects (similar to the limitation for setting border). We do not have a good way of setting borders for selections containing all, columns, or rows. (We also don't have bounds for borders, so we can't even fake it for clearing.)

Fix clear formatting removes borders if selection contains rects

---

quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx

Fixes number placement for kernel in the bottom bar.
Prod has it overlapping in a weird place (I forgot to update its placement when I moved it to the footer).

fix kernel running indicator

---

quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts

This fixes a bug with the new sendGetCellsLength function for strings that contain unicode characters

Fix string length calculation for unicode strings

---

quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
quadratic-core/src/grid/sheet/bounds.rs

closes #1602 
fixes all 4 bugs in #1602

fix: cmd + shift + arrow bugs

---

quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
quadratic-core/src/grid/sheet/bounds.rs
quadratic-core/src/wasm_bindings/controller/bounds.rs

jump to axis on Cmd + (Shift)? + Arrow keys

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
quadratic-core/src/controller/operations/cell_value.rs
quadratic-core/src/controller/operations/formatting.rs
quadratic-core/src/controller/user_actions/cells.rs
quadratic-core/src/controller/user_actions/formats.rs
quadratic-core/src/formulas/functions/mathematics.rs
quadratic-core/src/grid/js_types.rs
quadratic-core/src/grid/sheet.rs
quadratic-core/src/values/cellvalue.rs

Fixes number formatting bugs

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts

- decimal places for scientific notation is now 2 by default, can be changed
- number will should pound labels only if Overflow is set to clip or there is content in the next cell

fix: number formatting bugs

---

quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts

This fixes the starting viewport so the cursor shows properly at 0,0

start viewport at + 1 to ensure the full cursor shows

---

quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts

fix: when dragging on grid, ignore charts

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts

fix: typing text into a cell inline is wrongly interpreted as a formula

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
quadratic-core/src/formulas/functions/mathematics.rs
quadratic-core/src/formulas/functions/trigonometry.rs
quadratic-core/src/values/convert.rs

This should provide another layer of protection against #1678
Thank you @AyushAgrawal-A2 for pushing for this! I didn't realize the extra digits were coming from Rust.

Remove nonsense digits for `f64 -> BigDecimal`

---

quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx

fix: cell highlighting not working from Python/JS

---

quadratic-client/src/dashboard/components/OnboardingBanner.tsx

Buttons don't wrap and look weird on more narrow screens
Before:
After:

fix: button on onboarding banner

---

quadratic-client/src/dashboard/components/FilesListItem.tsx
quadratic-client/src/dashboard/components/FilesListViewControlsDropdown.tsx
quadratic-client/src/routes/teams.$teamUuid.index.tsx
quadratic-client/src/shared/shadcn/ui/tooltip.tsx

- For grid view, avatars are moved to far right with the secondary actions triggered moved to top right
- Everything stays the same on list view (avatar/secondary actions on the far right)
- Avatars always show on team list view, even if they are your files.
- Dates older than 24hrs switch from relative ("2h ago") to showing the date (Aug 24, 2024)
- Fixes a bug where tooltips could display behind other content
- Changes sort order label from "Last updated" to "Last modified" to match the file's meta which says "Modified ___ ago"

feat: team file list avatars (& misc. improvements)

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts

closes #1740 
bug happens after opening CodeEditor side pannel
ref: https://github.com/Microsoft/monaco-editor/issues/338#issuecomment-1763246584

fix: fill color should persist while editing

---

quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanel.tsx
quadratic-client/src/dashboard/components/NewFileDialog.tsx
quadratic-client/src/shared/components/connections/ConnectionDetails.tsx
quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
quadratic-client/src/shared/components/connections/Connections.tsx
quadratic-client/src/shared/constants/routes.ts

Today when you open a connection that won't load you get an error state that tells you to go check your connection details but the link is broken. It doesn't take you to the connection you're looking at, but rather the generic connection list.
This fixes this problem so clicking on it takes you to the details of the connection you were looking at
Note: the navigation is less-than-ideal because it refreshes the whole page. This is caused because we don't use URLs to make these navigations because this component is used in multiple places (in-app and in-dashboard) so it's hard to know which context we're navigating in. This problem would have to be considered in a separate a PR. At minimum this fixes the error state so it actually takes you to the connection details you're having a problem …

fix: navigate to connection from error state

---

quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts

Properly handles a console.log where there is no return statement. 
Sample code in code editor:
```js
console.log(1)
```
Cause: the return lineNumber was -1, which caused rust to panic when unpacking because it expected an u32.

Fix console.log bug in JS

---

quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts

fix: stacktrace for JS coderun in safari

---

quadratic-client/src/app/gridGL/cells/CellsSheets.ts
quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts

fix: javaScript charts not anchored to their cell when resizing columns

---

quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
quadratic-client/src/app/ui/menus/CommandPalette/CommandPaletteListItem.tsx
quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx

closes #1815
fixes: https://quadratichq.slack.com/archives/C06Q34HGV8A/p1724851083994249
Affected items - Code cell menu, Goto menu and command pallete
- clicking on command option should execute that option
- clicking on empty space should close command dialog and focus grid

fix: click to select on command dialog

---

quadratic-client/src/app/ui/menus/FeedbackMenu/FeedbackMenu.tsx
quadratic-client/src/shared/constants/urls.ts

Provide the generic contact link on the marketing website, so future contact changes don't require a re-deploy of the app (this is what we do generally in the app).
Before:
After:

fix: remove discord link

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts

fix: pressing arrow left next to = adds ref for left cell

---

Cargo.lock
quadratic-core/Cargo.toml

This reverts commit 4f614366e137f5de539282a90abda76528d16821.
Still using quadratichq/ts-rs (which is identical to the old HactarCE/ts-rs)

Revert "Use upstream ts-rs"

---

quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/EditMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/FileMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/FormatMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/HelpMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/InsertMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/ViewMenubarMenu.tsx

This fixes a subtle bug where the viewport receives pointermove events even when it is hovering over the top menu.

Fix hovering top-bar menu triggers canvas events

---

quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx

This fixes a minor bug where the drag point for the sheet tab was wrong (which was caused by the addition of the left navigation bar).
Current prod:
https://github.com/user-attachments/assets/64065c29-61c2-4e19-b7a4-07e0b664a230

Fixes bug with drag position when dragging sheet (in prod)

---

quadratic-client/.vscode/settings.json
quadratic-client/src/app/actions/actions.ts
quadratic-client/src/app/actions/insertActionsSpec.ts
quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
quadratic-client/src/app/keyboard/defaults.ts
quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx

added ctrl+; for time now; fixed bug with inserting while editor is open

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts

If you are editing a non-formula and change sheets, it properly saves the input before switching sheets. This fixes an annoying bug.

Change Sheet saves input (for non-formula inline editor)

---

quadratic-client/src/app/atoms/gridPanModeAtom.ts
quadratic-client/src/app/atoms/gridSettingsAtom.ts
quadratic-client/src/app/events/events.ts
quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
quadratic-client/src/app/gridGL/PixiAppEffects.tsx
quadratic-client/src/app/gridGL/QuadraticGrid.tsx
quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPanMode.ts
quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
quadratic-client/src/app/gridGL/interaction/pointer/PointerAutoComplete.ts
quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts

fix: sheet gets stuck in pan mode

---

quadratic-client/src/dashboard/components/OnboardingBanner.tsx

Button text shouldn't wrap, but buttons inside container should (when screens get narrow)

fix: getting started buttons wrapping issues

---

quadratic-client/src/dashboard/components/Empty.tsx
quadratic-client/src/routes/_dashboard.tsx
quadratic-client/src/routes/file.$uuid.tsx

On the dashboard or in the app, there are times you can hit a route that results in a screen where something went wrong.
Today it's not always clear that you might be hitting that error based on who you're logged in as.
For example, I go to `/teams/team-id-1` and it says "You can't access this team" and I think "I should be able to, that's weird..."
But the reality is that I can't access that team because I'm not logged in as the user I think I am when I hit that screen.
So this PR makes it a lot easier to infer why you might be hitting these screens, as it will show you you're currently logged in status (if you're logged in — if you're not logged in, e.g. an anon user, it won't show this).
Examples:
**You don't have permission to see team**
**Team not found**
**Unexpected error**

feat: show logged in user context

---

quadratic-client/src/shared/components/ShareDialog.tsx

When changing a user's role on a team, the UI updates immediately (while the change goes over the network).
https://github.com/user-attachments/assets/eea09ccd-6678-4dc0-8a24-f385e88e26f7

fix: optimistic UI when changing user role

---

quadratic-client/src/dashboard/components/DashboardSidebar.tsx
quadratic-client/src/dashboard/components/TeamSwitcher.tsx
quadratic-client/src/shared/components/Icons.tsx

- Make the dashboard background color the same as when you're in the app
- Tweak the team switcher to be purely about the current team (account stuff stays in the bottom)

feat: dashboard design tweaks

---

quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
quadratic-client/src/shared/utils/colors.ts

When you add install Quadratic as a standalone app, for example using Chrome:
It gets its own app bar. This needs to adjust to the theme color when the theme changes. This adds a `<meta>` tag that browsers use as a cue for this, so when you change it in the UI, the browser will update the app bar color too.
https://github.com/user-attachments/assets/10c3e6fd-9c57-44e1-8812-3243cad0aca9

fix: support theming in app bar

---

quadratic-core/src/date_time.rs

Fixes #2011
It was somehow parsing `1902-01` when comparing it to `%d %m %Y`, where `%Y` was assumed to be `-01` and spaces were discounted. There's probably a lot more work to be done on date/time parsing, but for now, I replaced the above with `%d %m %G`, where `%G` is looking for a four-digit year w/o negative values.
It now leaves the 1902-2, etc. as Text values.

ensure 1902-01 doesn't parse to date

---

quadratic-client/src/app/ui/components/Search.tsx

closes #1989
When searching on one sheet, if you manually change sheets, then the search dialog will search that sheet with the same options. When searching all sheets, then the behavior is the same as before.

Search dialog triggers when manually changing sheets

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts

fix: hyperlinks show up in text with a colon

---

quadratic-core/src/grid/file/v1_4/file.rs

fixes import of this charts example:

fix: all v1_4 code cell are imported as formula

---

quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx

4 new events:
- When user submits prompt in AI Analyst context
- When user submits prompt in AI Assistant context
- When user selects one of the zero state example prompts (in AI Analyst context)
- When the user changes the model (in either context)

feat: add mixpanel events for AI

---

quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorEmptyState.tsx

Two tiny one word changes 
Change 1: @davidfig thought this meant he was returning to the sheet as in closing the editor and returning to the sheet
Change 2: Adds a space in the AI panel where there currently is missing one, see attached image

Change code editor shortcut language from "Return to sheet" to "Output to sheet" and add missing space in AI security "Learn more dialogue" 

---

.vscode/settings.json
quadratic-api/src/routes/ai/anthropic.ts
quadratic-api/src/routes/ai/bedrock.ts
quadratic-api/src/routes/ai/openai.ts
quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
quadratic-client/src/app/ai/hooks/useQuadraticContextMessages.tsx
quadratic-client/src/app/ai/hooks/useToolUseMessages.tsx
quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
quadratic-client/src/app/ai/tools/aiToolsSpec.ts
quadratic-client/src/app/atoms/aiAnalystAtom.ts
quadratic-client/src/app/keyboard/defaults.ts
quadratic-client/src/app/ui/QuadraticSidebar.tsx
quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistant.tsx
quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx

Fixes for #2077, including:
- The logic is: if the user has _manually opened_ the AI chat 3 or more times, we cue off whether the sheet is empty or not. Otherwise we always show the AI Analyst open by default.
- It's worth noting that:
- The state of whether the AI is open or not is not a user preference and it is therefore lost on a page refresh (this is the same as the code editor, if you have the code editor open and you refresh the page, it's now closed which is the default state)
- This requires users manually open the AI analyst _at least 3 times_ by themselves, before we will stop showing it by default to them. We don't pay any heed to whether they've ever _closed_ the AI analyst. Only opened it.

fix: ai tweaks

---

quadratic-client/src/routes/_dashboard.tsx

Resolves #2100
When a user lands on the dashboard and has 0 teams, create a new team and then instead of sending them to the homepage for that team, create a new file for them and send them to the file
(Note: most of the time this will be because they are a _new_ user who hasn't been associated with a team yet, but it could also be for existing users who left the last team they were a part of).

fix: new users sent to empty file

---

quadratic-core/src/formulas/functions/datetime.rs
quadratic-core/src/values/convert.rs

Quadratic's implementation of `EDATE()` doesn't use serial numbers for dates because [even the Excel devs can't remember their own semantics correctly](https://github.com/user-attachments/assets/f665e565-22d0-4311-8d8d-e7f9c985d599), and we have a proper type system anyway.
Excel docs:
- [`EDATE()`](https://support.microsoft.com/en-us/office/edate-function-3c920eb2-6e66-44e7-a1f5-753ae47ee4f5)
- [`EOMONTH()`](https://support.microsoft.com/en-us/office/eomonth-function-7314ffa1-2bc9-4005-9d66-f49db127d628)

Add `EDATE()` and `EOMONTH()` formula functions

---

quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
quadratic-client/src/routes/examples.tsx
quadratic-client/src/routes/files.create.tsx
quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
quadratic-client/src/shared/components/ShareDialog.tsx
quadratic-client/src/shared/constants/routes.ts

Fixes #2147 
**To test**
Visit `/files/create?example=<example-file-url-in-prod>`
Example:
https://quadratic-git-duplicate-example-files.vercel.quadratic-preview.com/files/create?example=https://app.quadratichq.com/file/b90a8c28-4573-4073-bfaa-5bf14e808f51
Implemented by: https://github.com/quadratichq/quadratic-website/pull/240

feat: support duplicating example files from outside the app

---

quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
quadratic-client/src/app/ui/QuadraticSidebar.tsx
quadratic-client/src/app/ui/menus/BottomBar/SyncState.tsx
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
quadratic-client/src/shared/components/Icons.tsx
quadratic-client/src/shared/components/connections/ConnectionFormActions.tsx

Replace all instances of `<CircularProgress>` with our own custom spinner. This removes our dependence on the MUI package.
The new `<SpinnerIcon>` uses the `progress_activity` from our icon set and adds a spinning animation on it.

feat: remove dependence on mui for spinner

---

Cargo.lock
quadratic-core/Cargo.toml

A `cargo update` a day keeps the warnings away
(bumping wasm-bindgen from 0.2.87 to 0.2.100)

Fix wasm-bindgen warnings

---

quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx

Replicate: try to edit a formula with an error. You should not be able to hover over where the red triangle was and see the error information

Hide hoverCell when the cell has the inline editor open

---

quadratic-client/src/app/gridGL/cells/tables/Table.ts

Fixes: if you have a table without a table name but with columns, and move the viewport so the table is off screen, when it comes back on screen, the columns will not render.

Table columns properly show after culling

---

quadratic-api/src/ai/docs/PythonDocs.ts

Attempts to solve a few super common issues: 
- AI keeps trying to use non-Plotly libraries like Seaborn, explicitly outlines to not do so 
- AI often prints to console rather than defaulting to returning to the sheet (returning to the sheet always feels better than analyst outputting blank things because it prints stuff) 
- AI will often try to do a correlations analysis but has very high error rate doing this; informs AI to only do this when user asks for it 
- Explicit instruction to not try to use conditionals for return types (been trying this a lot lately, gives examples on how to do this properly) 
- Explicit instructions that you can't return multiple things per code cell (been trying to do this a lot lately where it will create a chart and then a dataframe and think both will get …

AI docs small change

---

quadratic-client/src/app/actions/selectionActionsSpec.ts
quadratic-client/src/app/grid/sheet/SheetCursor.ts
quadratic-client/src/app/gridGL/interaction/viewportHelper.ts

1. If viewport is slightly to the right of 1, and you keyboard over to 1, it used to not reset the viewport to the start.
2. When you select with shift+arrow key, the viewport moves correctly

Minor fixes to ensure visible

---

quadratic-client/src/routes/teams.$teamUuid.index.tsx
quadratic-client/src/shared/components/Avatar.tsx

This changes the avatars to use shadcn colors as well as removes usage of the MUI `<Avatar>` and `<AvatarGroup>` on the team page. Instead we rely on our own internal `<Avatar>` component which is now sensitive to light/dark mode.
Part of an on-going effort to remove MUI components and standardize on shadcn.

chore: remove mui avatars

---

quadratic-client/src/shared/components/ShareDialog.tsx

fix: make "copy link" correct from the dashboard

---

quadratic-api/src/ai/docs/QuadraticDocs.ts
quadratic-shared/ai/specs/aiToolsSpec.ts

Through experimentation came to conclusion this change isn't best done by editing tools. Seems best done by editing broader docs so it's included in every prompt and AI can reply to the user directly that it can't add code to tables.

Docs update for AI to not try to stick formulas/code into tables

---

quadratic-api/src/ai/docs/QuadraticDocs.ts

AI shouldn't try to explain the data or code its generating in the chat. 
When the AI tries to repeat back the data or code it's generating it's often incorrect. We've gotten a lot of user reports where people have been confused by the discrepancy. 
**Prompts for testing (these prompts try to say the values nearly 100% of the time in prod)** 
"Create a sample product analytics dataset with monthly active users, conversion rate, revenue, session duration, and churn rate for 2024, then create a dual-axis chart showing the relationship between active users and revenue growth."
"Create some sample sales data and create a chart plotting it."

AI shouldn't try to explain the data or code its generating in the chat 

---

quadratic-core/src/controller/operations/cell_value.rs
quadratic-core/src/controller/user_actions/cells.rs

Temporarily disables table growing to the right and bottom when new data is added via a user or AI.

Temp disable auto expansion

---

quadratic-client/src/shared/components/Avatar.tsx

The `className` prop wasn't being passed to the `<Avatar>` component, so context-specific UI overrides weren't being applied correctly. For example, grouped avatars weren't spaced/overlaid correctly.
Here's an example from prod:
And on local:
**The above are examples of what it SHOULD NOT look like.** Here's what it looks like in the current preview branch:

fix: avatar spacing

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

#2455 
This adds all the issue & PR templates outlined in #2455. These include bug, feature, and PR templates. 
This doesn't touch any relevant code and doesn't require testing. 
You can review how this feels by visiting [this repo](https://github.com/luke-quadratic/template-testing/). This repo includes the issue and PR templates in this PR; to test just play with creating an issue or PR. 
N/A

Add issue templates & PR template

---

infra/aws-cloudformation/quadratic-preview.yml

No open issues for this
This PR disables Global Accelerator used in PR previews, we are hitting the account limit of 20 global accelerators and preview deployments are failing.
Infra changes only, previews should deploy and work as normal
No

infra: disable global accelerator for previews

---

quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/TableColumnHeaderRename.tsx
quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/TableRename.tsx
quadratic-client/src/app/ui/hooks/useRenameTableColumnName.tsx
quadratic-client/src/app/ui/hooks/useRenameTableName.tsx
quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeaderLabel.tsx
quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
quadratic-core/src/a1/a1_context/table_map.rs
quadratic-core/src/a1/js_selection/validate_name.rs
quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
quadratic-core/src/grid/data_table/mod.rs
quadratic-core/src/grid/sheet.rs

Allow renaming of Sheet names, tables, and columns w/only changes to case

---

quadratic-api/src/ai/docs/JavascriptDocs.ts
quadratic-api/src/ai/docs/PythonDocs.ts
quadratic-api/src/ai/docs/QuadraticDocs.ts

Edits AI docs in following ways: 
**Python docs:** adds column range reference 
**JS docs:** adds table refs and updates some incorrect language 
**Quadratic docs:** adds instructions stating code isn't global; attempts to fix a common error where thinking mode generates code that it thinks it can reference in subsequently created code
Realized this was missing from [this discussion](https://community.quadratichq.com/t/how-do-you-reference-cells-from-programming-languages/17/2) with user

AI refs docs update

---

quadratic-api/prisma/migrations/20250312165630_remove_unused_tables/migration.sql
quadratic-api/prisma/schema.prisma

The old QFile table takes a ton of space in our database, this cleans up unused tables and will help our database migration go faster.
We have backups of this data.

remove legacy database tables

---

quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
quadratic-core/src/sheet_offsets/resize_transient.rs

closes #2375 
fixes the linked issue
no
no

fix: resizing a grid column/row does not properly reset when pressing escape

---

quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx

Currently it's not clear that these are examples if you only read the headers (not the subheaders). 
Changed to prompts that work both if the sheet is empty and if the sheet already has users data. If they click on create a chart it will either add example data if the sheet is blank or it will chart the users data on the sheet.

improve the starting prompts

---

quadratic-client/src/app/gridGL/UI/HtmlPlaceholders.ts

#2499 
Chart icons are no longer kept after rendering

Cleans up chart icons after thumbnail

---

.github/workflows/preview-build-deploy-images.yml
infra/aws-cloudformation/quadratic-preview.yml

none
- reverts https://github.com/quadratichq/quadratic/pull/2464 , we have a higher number of global accelerators available, preview should not fail because of global accelerators quota exceeded
- adds compression to preview images, saving and loading cache should be faster now reducing build time

infra: enable global accelerator for previews

---

quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx

When hovering an error, then clicking the cell with the error the error disappears. This fixes that.
New Behavior 
https://github.com/user-attachments/assets/932a9fb2-204c-446e-815c-9b32534e8cfd
Old Behavior
https://github.com/user-attachments/assets/8c565529-5ff8-4460-9d5c-80661e8df474

Nit: Fix Hover Error + Click Cell, Error Disappears

---

quadratic-api/src/ai/docs/JavascriptDocs.ts
quadratic-api/src/ai/docs/PythonDocs.ts

Gabe referenced a user in Slack who was annoyed that code tried to export their file for them when asked, but it didn't work. This gives AI clear instructions that they can't import/export files with Python (and JS) in Quadratic with instructions on how this can be performed in Quadratic. 
Please review docs change for correctness.

Instruct Python (and JS) to not attempt to import/export files in code

---

quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
quadratic-client/src/app/gridGL/pixiApp/viewport/Wheel.ts

This does a few things to the Viewport:
- While dragging prevent snap back until dragging is released (when pressing space to drag and beyond the bounds.)
- Don't allow momentum scrolling past the bounds, this was a bit glitchy looking. You can still zoom beyond the bounds, and drag past the bounds.
- Reduce the time after zooming to snap back.
This also makes some changes to the GridHeadings:
- always shows A and 1 heading labels
- on the numbered axis adds a step to count by 2s showing 1, 3, 5, etc
- on the vertical axis, make the counting by numbers that fit into the alphabet 
- fixes a bug where if you zoom out past 13% all the letter labels start to disappear

Viewport Improvements

---

quadratic-api/src/storage/storage.ts
quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts

File storage now uses presigned urls same as s3, so same file permissions flow works now for shared files on self-hosted app

fix: use presigned urls for file-storage

---

quadratic-client/src/app/actions/actions.ts
quadratic-client/src/app/actions/actionsSpec.ts
quadratic-client/src/app/actions/dataTableSpec.ts
quadratic-client/src/app/actions/insertActionsSpec.ts
quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/InsertMenubarMenu.tsx
quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/MenubarItemAction.tsx

Fixes https://github.com/quadratichq/quadratic/issues/2323
Adds `Insert -> Table` to the toolbar menu.
`Table` is disabled when a single cell is selected.

Add Insert->Table to the toolbar menu, disable for single cells

---

quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts

Firefox did not allow clicking on the sheet.
`TouchEvent` doesn't exist in Firefox, so you can't use `instanceof` w/o throwing an error.

Fixes firefox pointer issue

---

quadratic-core/src/grid/contiguous/contiguous_2d.rs

just utility functions. no effect on end users.

Add `Contiguous2D::is_all_default_in_rect()`

---

Cargo.lock
quadratic-core/src/grid/data_table/row.rs

Resolves this error in data dog: 
> Time | Host
> T-----------------------------
> T17:39:52 UTC | i-0e01831a0b83cbb77
> Tnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> T-----------------------------
> T17:39:52 UTC | i-0e01831a0b83cbb77
> Tinsertion index (is 42) should be <= len (is 41)
> T-----------------------------
> T17:39:52 UTC | i-0e01831a0b83cbb77
> Tthread 'tokio-runtime-worker' panicked at /quadratic/quadratic-core/src/grid/data_table/row.rs:52:28:
Also adds a test to validate and avoid regressions.

Check for out of bounds on the display buffer when inserting a row

---

quadratic-client/src/app/actions/insertActionsSpec.ts

Fixes https://github.com/quadratichq/quadratic/issues/2459
This is happening with any supported file when the next import has the same name. It's due to the onChange event not firing in these cases.

bugfix: clear GridFileInput value after import

---

quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx

Fixes #2432 
Renaming sheet should not get stuck. If clicked away with invalid entry, then it will revert. Otherwise, it should return to the edit.

Fix stuck in rename

---

quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts

Fixes #2590 
Code peek (when turned on) should not show when hovering data tables

Code peek should not appear on data table

---

quadratic-core/src/grid/sheet.rs

Fixes #2494 
For ctrl+arrow, we treat single-value tables the same as sheet values, so we skip over multiple rows or columns.

Ignore table edges for tables that are of size 1

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts

Fixes #2258 
In prod, if you press shift+enter when editing a cell when the cursor is in the middle of the text, then a line break is added at that point. This PR removes that behavior.

Ensure shift+enter in the inline editor doesn't add a linebreak

---

quadratic-api/src/ai/docs/PythonDocs.ts

Seeing lots of try-except usage from Analyst (especially in Thinking mode). These are not useful and make AI provide confusing results. 
AI should attempt things and if they fail they need to surface as errors in the sheet so AI knows to fix. If it's stuck in a try-except the error doesn't get surfaced and the AI doesn't know it needs to automatically perform a fix.

Keep AI from using try-except blocks

---

quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts

Fixes #2676
Change the order of pointerDown so heading is checked first.
Check all the mouse downs on the sheet.

change order of pointerDown.heading

---

quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
quadratic-client/src/shared/components/ABTest.tsx

Run an A/B test using Mixpanel on the copy for upgrading to Pro. 
Uses `team.uuid` to determine control vs variant group, so a user will always see the same one.
Control
Variant

add an ab test on ai exceeded copy

---

quadratic-api/src/ai/docs/PythonDocs.ts
quadratic-api/src/ai/docs/QuadraticDocs.ts

Response to report from Cole that he got two comments in a single day from AI trying to tell people incorrect info about PDFs. 
Edits the following: 
- Quadraticdocs: adds clarity to file imports 
- Pythondocs: adds clarity to file imports

Make AI chat aware of PDF capabilities 

---

quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
quadratic-core/src/controller/active_transactions/pending_transaction.rs
quadratic-core/src/controller/execution/receive_multiplayer.rs

closes #2623
there are side effects (mostly rendering) on transaction which happen in `finalize_transaction`, these were not happening correctly for multiplayer transactions
now `finalize_transaction` is called for all transactions (mp, rollback, reapply, etc)

fix: rendering of multiplayer transactions

---

.github/workflows/qa-deploy.yml

Fixes docker image tag to `pr-qa` which is used by pulumi to deploy latest images

fix: qa docker image tag

---

quadratic-connection/Cargo.lock
quadratic-core/src/controller/operations/cell_value.rs
quadratic-core/src/grid/data_table/column.rs
quadratic-core/src/grid/data_table/row.rs

Fixes: https://github.com/quadratichq/quadratic/issues/2739
Expanding a table that is sorted causes a major issue, see attached vid for recreation (sort table and then try to auto expand on bottom)
@luke-quadratic your call here

bugfix: Auto-expand on sorted table causes disappearing data

---

quadratic-client/src/app/gridGL/interaction/pointer/PointerLink.ts

When you hover a tooltip, it shows the function rather than the executed label.

fix: tooltip shortcut label

---

quadratic-client/src/app/actions/dataTableSpec.ts
quadratic-core/src/controller/execution/run_code/mod.rs
quadratic-core/src/grid/data_table/mod.rs

Fixes https://github.com/quadratichq/quadratic/issues/2637
Fixes https://github.com/quadratichq/quadratic/issues/2516
IDK if this will break current QA Wolf tests

Python data table name states

---

quadratic-shared/ai/models/AI_MODELS.ts

switch to using claude on bedrock, gcp is throwing `RESOURCE_EXHAUSTED` error

chore: switch to claude on bedrock

---

.github/workflows/production-github-release.yml

debugging failure of last run by adding write permission to the workflow
ref: https://github.com/quadratichq/quadratic/actions/runs/14644893695/job/41096406151****

fix: add write permission to Github Release workflow

---

quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts

Fixes flashing cursor at 0,0 when double clicking inside a data table

---

quadratic-api/src/routes/v0/feedback.POST.ts

We're likely filtering out a lot of great feedback by having the min be 30 characters. 
E.g. "Please build secrets!" wouldn't make it through as that's only 20 characters.

Reduce webhook feedback message limit 

---

quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/PixiRename.tsx

Fixes #2851
Renaming a table from the context menu works on first try.

Fixes bug with rename table name

---

quadratic-client/src/routes/files.create.tsx

adds empty Component to silence sentry errors

fix: add empty component to file/create route

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts

Fixes #3056
Limits rendering to 1,000 characters per cell (doesn't change the value that `getCells` receives)

Limits text rendering to 1000 characters

---

quadratic-client/src/app/gridGL/cells/tables/Tables.ts
quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts

When viewport is scrolled, the floating table headers may be misplaced during thumbnail generation.
Old:
New:

Fixes placement of table headers when generating thumbnail

---

quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
quadratic-client/src/app/ui/QuadraticApp.tsx

This fixes a timing bug, where the app may load before the grid settings (eg, Show AI on Startup) finishes loading.

Ensures GridSettings are loaded before app starts

---

quadratic-connection/Cargo.toml
quadratic-connection/src/sql/snowflake.rs
quadratic-rust-shared/Cargo.toml
quadratic-rust-shared/package.json
quadratic-rust-shared/src/lib.rs
quadratic-rust-shared/src/sql/cockroachdb_connection.rs
quadratic-rust-shared/src/sql/mysql_connection.rs
quadratic-rust-shared/src/sql/snowflake_connection.rs
quadratic-rust-shared/src/test/mod.rs

Fixes issue captured in DataDog:
```
Time | Host | Message
-----------------------------
09:02:43 UTC | i-0621c2a111c62dfe6 | could not read from file /quadratic/quadratic-rust-shared/fixtures/snowflake-connection.yml: Custom { kind: NotFound, error: VerboseError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, message: "could not open `/quadratic/quadratic-rust-shared/fixtures/snowflake-connection.yml`" } }
-----------------------------
09:02:43 UTC | i-0621c2a111c62dfe6 | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/httpmock-
```
I removed mocks from the Snowflake tests in favor or hitting an actual database.  We're having issues with MFA, which makes CI test untenable.   I'm ignoring snowflake tests so that we can fast track …

Fix snowflake in production

---

quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts

fix: underline underlines empty cells in tables

---

quadratic-rust-shared/src/sql/bigquery_connection.rs

Fixes https://github.com/quadratichq/quadratic/issues/3281
When selecting the Query Selected Table button in the UI, the test Dataset was hard-coded rather than being pulled from the connection config. With this PR, selecting the Query Selected Table button should show the correct Dataset in the query.
1. Create BigQuery connection
1. With a cell highlighted, open connections and select BigQuery connection
1. For any table, click on the Query Selected Table button
1. The correct dataset should display in the window

Fix hard-coded biqquery dataset in Query Selected Table

---

quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
quadratic-core/src/grid/data_table/column.rs
quadratic-core/src/grid/data_table/column_header.rs

fix: inserting columns can create duplicate table column names

---

quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
test/e2e/src/spreadsheetTables.spec.ts

Fixes an issue in production where selecting a sheet from the go to menu would change the sheet _but not_ close the menu.
https://github.com/user-attachments/assets/098d6139-ea57-47d9-be76-e1828064a56f
- Open file
- Create multiple sheets
- Switch sheets via the go to menu and see that the menu closes when you choose one

fix: go to menu sheet selection closes menu

---

quadratic-api/src/routes/v0/teams.$uuid.connections.$connectionUuid.PUT.test.ts
quadratic-api/src/routes/v0/teams.$uuid.connections.$connectionUuid.PUT.ts
quadratic-client/src/shared/components/connections/ConnectionFormSemantic.tsx
quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx

- [bug] Fix where "Warehouse" and "Role" values were not showing up when saved
- [bug] Fix where "Semantic description" could not be removed once added
- [feature] Hides (large) UI around adding a semantic description behind a on/off toggle
- Create a snowflake connection with "Warehouse" and "Role" values
- Go back to editing the connection and ensure that the values for those fields are what you saved
- Remove the "Warehouse" and "Role" values you added
- Go back to editing the connection and ensure the those two fields are empty now
- Toggle ON semantic description, enter one, and save it. Go back to editing the connection and ensure you can see the value you added.
- Toggle OFF the semantic description, save it. Go back to editing the connection and ensure the toggle is OFF and if you …

fix: semantic description & snowflake connection

---

quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts

Fix heading auto resize

---

quadratic-client/src/shared/utils/sentry.ts

Turn on replays in Sentry.
Tested this locally by adding the `VITE_SENTRY_DSN` value and [my recording ended up in Sentry](https://sentry.quadratichq.com/organizations/quadratic/replays/46e3ce1202674f6fa27ebc5dd67f7aa2/?project=1&query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29)
Can test in the preview branch by changing the same env var, or just ship to prod and see it turn on.

feat: turn on sentry replay

---

quadratic-api/src/ai/handler/ai.handler.ts

Errors not getting sent to backup model on Max model (Vertex) because of the thinking config.

Errors not getting caught on Max model (Vertex) 

---

quadratic-client/src/shared/utils/sentry.ts

We're getting tons of "Anonymous" user replays in Sentry because it's capturing people uploading files from the marketing site
We don't want to log any of these sessions, so we exclude any paths that match that string [based on Sentry's config](https://docs.sentry.io/platforms/javascript/session-replay/configuration/)

fix: update sentry replays to exclude iframe
